### ISSUE TITLE
Wrong/misleading title for page navigation setting 

### ISSUE THREAD

**Issue by crash0verride** [sulu/sulu-standard#396]
Current title is "Navigations Kontexte" in german, which is misleading from a user point of view.

I suggest: 
"Verlinkung in Navigation" in german or "Link in navigation" in english

![bildschirmfoto 2015-01-19 um 14 22 31](https://cloud.githubusercontent.com/assets/3469973/5801039/b6ce63d2-9fe6-11e4-9cde-70f2fe5463a3.png)

**Comment by danrot** [comment]
@berndhep Is that translation ok?

**Comment by berndhep** [comment]
@danrot Nein, es sollte heissen: Shadwo-Seite und/oder Ghost-Seite

**Comment by danrot** [comment]
@berndhep I think he is talking about the navigation contexts :-)

**Comment by berndhep** [comment]
@danrot Ok, I see. He's right. Please take the suggested translations. (But also, correct the "Shadow" section)

**Comment by wachterjohannes** [comment]
"Zeige Seite in" / "Show page in" and "Shadow Seite"
