### ISSUE TITLE
Dedicated inputs for Social Media platforms (Contact Bundle)

### ISSUE THREAD

**Issue by berndhep** [sulu/sulu-standard#508]
Users should be able to add input fields for SoMe handles in Contacts bundle.

Facebook
Twitter
LinkedIn
Xing
Google+
Disqus
Snapchat
Tumblr
Pinterest
YouTube
Instagram
WhatsApp
Other

**Comment by danrot** [comment]
Fixed in https://github.com/sulu/sulu/pull/3354
