### ISSUE TITLE
Feedback on First Run Experience

### ISSUE THREAD

**Issue by carltongibson** [sulu/sulu-standard#519]
I'm set up with a development version of Sulu now. Great job. It seems awesome!

I had two issues getting started: 
- PostgreSQL support needs some love. #516 
- I forgot to set the `SYMFONY_ENV` so had a mysterious `getTheme on a non-object` error trying to run locally #518 — a decent error message would help there. 

My only other observation beyond these is that it's _a bit of a pain_ to have to set up Nginx or Apache (+ FastCGI, on the documented approach) just to try out the project. 

It would be great if there was a bundled `router.php` so that users could just clone, install dependencies, run the build script, and so on before using the development server to get up and running.

**Comment by danrot** [comment]
Ah, this is what all of this was about :smile: Actually there are already router scripts located at `app/config/router_admin.php` and `app/config/router_website.php`, so it can easily be run with `app/console server:run -r app/config/router_admin.php` and accessing `localhost:8000` afterwards. I guess this information is missing in the documentation (or at least at the wrong place, there is a mention of this at http://docs.sulu.io/en/latest/developer/behat/getting-started.html#running-the-tests). /cc @joemoe

**Comment by carltongibson** [comment]
> ... there are already router scripts...

Ah-ha! "Testing" was my next reading topic. :-)

A quick `app/console server:run -r app/config/router_admin.php` gives me `No route found for "GET /"`. (But now I know where to look I can experiment there.)

Thanks for the help getting off the ground.

**Comment by danrot** [comment]
No problem. But it would really be interesting to add these to the getting started documentation, for people who really just want to try it out as fast as possible.

**Comment by bschmitt** [comment]
+1

**Comment by chirimoya** [comment]
https://github.com/sulu-io/sulu/issues/2078

**Comment by alexander-schranz** [comment]
This linked issue seems to be solved and since introducing sulu-minimal php development server works without problems
