### ISSUE TITLE
Add function: Delete language

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#523]
Sometimes we need a functionality to delete only the language-template in sulu - not the whole template (with the other translates).
Can you add this function please?

![bildschirmfoto 2015-10-02 um 08 31 11](https://cloud.githubusercontent.com/assets/8446518/10240716/fecf8644-68df-11e5-85d7-cdb613e2de51.png)

**Comment by chirimoya** [comment]
https://github.com/sulu-io/sulu/issues/431

**Comment by danrot** [comment]
This is a duplicate of https://github.com/sulu/sulu/issues/431, and I close this issue, since the other one is in the correct repository.
