### ISSUE TITLE
Subpages don't update URL if parent page restores a history URL

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#538]
You have a content-page with subpages. If you change the url of the content-page (from `/abc/` to `/def/`), all subpages will have the same url (now `/def/subpage1`). 

BUT if you change the url of the content page with the history option (as example change back from `/def/` to `/abc/`), then the subpages doesn't have the same url than the content page (the subpages have the url `/def/subpage1`). You can change whatever you want - but the url never will be changed again on the subpages.

Same problem, if you deleted an old history option and set it new (with the same spelling).

**Comment by dmetzler1988** [comment]
Same problem occurs if you have a existing subpage in one language (en) and create a empty template in another language (de). Then switch the tab (to SEO for example) and switch back to content tab. Type in a new title. So the address haven't the title-name or the correct url (without the parentpage).

**Comment by alexander-schranz** [comment]
Can't reproduce, child seems to be correctly updated.
