### ISSUE TITLE
Analytics keys also on custom routes/error-pages

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#594]
please check that the custom keys (analytic-key) also available on the custom routes and error-pages

**Comment by alexander-schranz** [comment]
I created in my projects an abstract controller which will write the RequestAnalyzer Params into the view. Maybe something like this can be added to sulu: https://gist.github.com/alexander-schranz/b81c0f8f54ce04a00559

**Comment by wachterjohannes** [comment]
there is a new feature in 1.2-dev which enables you to manage analytics in backend.

This should be tested with custom-routes and error-pages (maybe with flag because not everyone would like to track 404)

**Comment by danrot** [comment]
@wachterjohannes I would not introduce a flag for that, because I can't imagine that somebody would not be interested in the fact that his clients see a lot of error pages.

**Comment by danrot** [comment]
@wachterjohannes And can you link this issue in your PR? Not that it gets lost again.

**Comment by wachterjohannes** [comment]
the analytics PR is already merged so we have to test this before 1.2 and fix it if its not working

**Comment by danrot** [comment]
Can you evaluate that soon? So that we can close this issue, in case it already works.

**Comment by webmozart** [comment]
@dmetzler1988 Could you check whether this is still an issue please?

**Comment by wachterjohannes** [comment]
i will check this

**Comment by wachterjohannes** [comment]
On error-pages there are already the analytics. On the custom-url there is this PR which fixes this issue https://github.com/sulu-io/sulu-standard/issues/594

**Comment by danrot** [comment]
@wachterjohannes As I understand this @dmetzler1988 is talking about registering own symfony routes, instead of using the custom url feature. I'll check with the search controller if this works.

**Comment by wachterjohannes** [comment]
there it works if you have registered your routes with the portal loader.
