### ISSUE TITLE
little bug on file-size in media-section

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#597]
if you upload some files, you can see that the file-size is displayed in a different format sometimes.
(see attached image)
![bildschirmfoto 2016-01-27 um 15 32 41](https://cloud.githubusercontent.com/assets/8446518/12646263/398b924a-c5cf-11e5-92c7-6262dc7bb208.png)

**Comment by danrot** [comment]
@dmetzler1988 Are you talking about the filesize `1.00e+3 KB`?

**Comment by dmetzler1988** [comment]
@danrot yes, these filesize i meant

**Comment by danrot** [comment]
@dmetzler1988 Do you still have the image that caused this issue? Cannot reproduce it on my own, I think it needs a very certain filesize.

**Comment by dmetzler1988** [comment]
i see now (with the newer sulu-version 1.1.8) that the elements in the screen aren't images. they are movies. This file where the error occurs is a mp4 with 1MB.

i have test it now with a own file with ~ 1MB. same error.
