### ISSUE TITLE
Copy .dist files automatically on fresh install

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu-standard#622]
The documentation explains that .dist files need to be copied in order to get Sulu working. This should be automated in a post-install/update hook instead. Users who install Sulu for the first time shouldn't need to care about this.

**Comment by dantleech** [comment]
Made a PR https://github.com/sulu-io/sulu/issues/2123

**Comment by danrot** [comment]
Fixed with the introduction of sulu-minimal.
