### ISSUE TITLE
Clearly communicate login username/password

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu-standard#624]
At the moment, it's really hard to find the username/password that can be used to access the backend by default (especially in the online demo). The demo user/password should be visible somewhere.

**Comment by wachterjohannes** [comment]
the credentials are visible in the right dow corner on the demo. maybe it should be highlighted more.

**Comment by harikt** [comment]
@wachterjohannes the good idea will be provide the username / password on the form :-) .  So why do you guys need to worry about showing them ;-) .

And what is the current server configuration of the demo ?

**Comment by danrot** [comment]
@harikt About which server configuration are you talking? And I don't think it's easy to show this in the login form, since we don't have any texts there yet. But yeah, we should probably think about something.

**Comment by harikt** [comment]
@danrot http://demo.sulu.io/

**Comment by danrot** [comment]
@harikt I know which server you are talking about :-) I am just not sure what kind of server configuration here you want to know. In case you are talking about the user credentials, these are demo/demo.

**Comment by harikt** [comment]
cool.

May be its just me :) .

**Comment by chirimoya** [comment]
We should update the translations for the demo page so that the placeholders show the username and password on the login page.

**Comment by alexander-schranz** [comment]
fixed in the new http://sulu.rocks [demo](https://github.com/sulu/sulu-demo)
