### ISSUE TITLE
Improve design of online demo

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu-standard#625]
The current design of the online demo is functional, but not quite beautiful. I think the design of the demo should be improved to be more convincing.

**Comment by danrot** [comment]
We also already thought about simply using the content of www.sulu.io for the demo. WDYT about that? Would probably also mean that we should try to use the newer features in this installation.

**Comment by webmozart** [comment]
@danrot I'd rather not do that, as it could be confusing as to which is the official content and which isn't.

**Comment by alexander-schranz** [comment]
fixed with the new sulu.rocks demo
