### ISSUE TITLE
Category admin fails to load once populated

### ISSUE THREAD

**Issue by camburns** [sulu/sulu-standard#631]
The category admin list/overview page (not the detailed / edit cat page) fails to load category contents once it's populated.

It shows all the normal admin UI components but simply shows a loading animation in place of categories as if requesting content from the server.

I've tried on my project implementation of Sulu and also with a fresh install from sulu-standard (today) - same result.

Environment:
Localhost, Mac Air 2012, El Capitan,
Stock PHP 5.5 install, MYSQL, Chrome, 
Sulu-standard

Hope this can be fixed in a future update.

**Comment by camburns** [comment]
Found it in the AJAX calls:

URL
http://sulu.lo/admin/api/categories?flat=true&sortBy=depth&sortOrder=asc&locale=en_us&fields=id,name

Response:
{"code":0,"message":"An exception occurred while executing 'SELECT c0_.id AS id_0, (CASE WHEN c1_.translation IS NOT NULL THEN c1_.translation ELSE c2_.translation END) AS sclr_1, c0_.depth AS depth_2, c3_.id AS id_3, c4_.id AS id_4, (CASE WHEN c1_.locale IS NOT NULL THEN c1_.locale ELSE c2_.locale END) AS sclr_5, c0_.default_locale AS default_locale_6 FROM ca_categories c0_ LEFT JOIN ca_category_translations c1_ ON c0_.id = c1_.idCategories AND (c1_.locale = 'en_us') LEFT JOIN ca_category_translations c2_ ON c0_.id = c2_.idCategories AND (c2_.locale = c0_.default_locale) LEFT JOIN ca_categories c3_ ON c0_.idCategoriesParent = c3_.id LEFT JOIN ca_categories c4_ ON c0_.id = c4_.idCategoriesParent WHERE c0_.id IN (?) GROUP BY c0_.id ORDER BY c0_.depth ASC' with params [5]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sulu.c1_.translation' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"}

wondering if it's my mySQL config...

**Comment by camburns** [comment]
Yup, not working on sulu cloud either.

**Comment by camburns** [comment]
In fact I've tried viewing articles I've created - doesn't work, viewing tagged articles I've created and tagged - doesn't work and now getting a bunch of permission denied errors. I thought this bundle was "production ready"?

**Comment by wachterjohannes** [comment]
@camburns which version of mysql do you use? could you try to disable sql mode "only_full_group_by"?

**Comment by camburns** [comment]
Mysql version:
+-------------------------+------------------------------+
| Variable_name           | Value                        |
+-------------------------+------------------------------+
| innodb_version          | 5.7.11                       |
| protocol_version        | 10                           |
| slave_type_conversions  |                              |
| tls_version             | TLSv1,TLSv1.1                |
| version                 | 5.7.11                       |
| version_comment         | MySQL Community Server (GPL) |
| version_compile_machine | x86_64                       |
| version_compile_os      | osx10.9                      |
+-------------------------+------------------------------+

**Comment by camburns** [comment]
Solution:
run in MySQL
SET global sql_mode = '';

however you may want to do some reading about sql_mode first:
http://www.mysqlfaqs.net/mysql-client-server-commands/what-is-sql-mode-in-mysql-and-how-can-we-set-it

----
Thanks @wachterjohannes, however the issue in sulu-cloud still exists in the PGSQL DB - is this something I should address in the sulu-cloud repo? Also concerned this issue may deter sulu newbies - should these queries be rewritten for stricter mysql_modes?

**Comment by wachterjohannes** [comment]
@camburns we use standard sql_mode wich is fully supported by doctrine. if you want to use another sql_mode you have to address issues about that maybe in doctrine.

PGSQL is currently not fully supported because of another bug which was found by @carltongibson in #522

**Comment by chirimoya** [comment]
https://github.com/sulu-io/sulu/issues/1797

**Comment by danrot** [comment]
Closing this issue in favour of https://github.com/sulu/sulu/issues/1797
