### ISSUE TITLE
Sulu urls language behaviour

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu-standard#632]
I'm questioning the current handling of the returned content urls.
Default Webspace setup `sulu.lo/{localization}`

Sulu currently return all urls without the location. So I want to use smart_content need to call `sulu_content_path` I want to use Internal links need to call `sulu_content_path` want to get my current url or just the other language `urls` need to call `sulu_content_path`. 

So the data of the view are just incomplete. And the url prefixes are needed.

I know that symfony it self handles it also so that you need to call `path` but there the advantage is that all urls in all language are the same which is in sulu to 99% not that english or e.g german have the same urls so you cant just call `path('...', {_locale: 'de'}).

In my opinion sulu should return the correct urls to the view. 

For the sitemap it could be handled over extension for the domain prefix but the sitemap is not a daily business thing and also will not be changed in any project.

**Comment by danrot** [comment]
That's basically the same issue as https://github.com/sulu-io/sulu-standard/issues/365, I am closing the other one, since this one describes the problem in more detail.

**Comment by danrot** [comment]
Closed in favor of sulu/sulu#3133
