### ISSUE TITLE
Max-value for snippet content type

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#638]
| Q | A |
| --- | --- |
| Bug? | no |
| Version Used | 1.1.10 |
| New Feature? | yes |

It would be nice if we can set a max-value for snippets (like smart-contents) on a content page.

**Comment by wachterjohannes** [comment]
related to https://github.com/sulu-io/sulu/issues/451 . we thought about adding a new content type with a different ui.

**Comment by danrot** [comment]
https://github.com/sulu-io/sulu/issues/451 is a different problem IMO. Here you might also want to set the max value to e.g. 3, so there won't be a separate UI element. And I don't know if we need a different UI element for single snippets...

**Comment by wachterjohannes** [comment]
that should be discussed with @berndhep

**Comment by dmetzler1988** [comment]
Current status (Sulu 2.0):  
With the property type `snippet_selection` there is currently no setting option to define the maximum number of snippets.

Currently there is only the possibility to limit this via the TWIG output and to store an info text in the Sulu admin area about the limitation.

**Comment by alexander-schranz** [comment]
This is related to sulu/sulu#2938 will close this one as the other is in the correct repository.
