### ISSUE TITLE
max-value parameter for media_selection

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#639]
| Q | A |
| --- | --- |
| Bug? | no |
| Version Used | 1.1.10 |
| New Feature? | yes |

it would be nice if we can set a parameter for max-value on media_selection (like smart-content).

**Comment by wachterjohannes** [comment]
related to https://github.com/sulu-io/sulu-standard/issues/638

**Comment by alexander-schranz** [comment]
Closing this in favor of sulu/sulu#2938
