### ISSUE TITLE
QueryBuilder for select Snippet by field

### ISSUE THREAD

**Issue by Doum-Super** [sulu/sulu-standard#649]
I want to implement a QueryBuilder  which select snippets from database by field.
I have do this in my controller:

`$dm = $this->get('sulu_document_manager.document_manager');
 $builder = $dm->createQueryBuilder();
         $builder
             ->setLocale('fr')
             ->from()
                 ->document('full', 'f')
             ->end()
             ->where()
                 ->eq()->field('f.author')->literal('name_of_author');
         $results = $builder->getQuery()->execute();
         $this->assertEquals(1, count($results));
         return $builder;`

I obtain this error:
Not implemented

**Comment by dantleech** [comment]
The Query Builder is indeed not yet implemented, there is an open PR:

    https://github.com/sulu-io/sulu/pull/1863

**Comment by chirimoya** [comment]
@Doum-Super ... as soon as the QueryBuilder PR is merged you should be able to use it as expect.

**Comment by dantleech** [comment]
@Doum-Super where did you find out about the Query Builder API? It hasn't been documented yet AFAIK
