### ISSUE TITLE
Override SnippetRepository

### ISSUE THREAD

**Issue by Doum-Super** [sulu/sulu-standard#650]
How can i override sulu SnippetRepository.php ?

**Comment by wachterjohannes** [comment]
if it is enough for you you could use the parameter `%sulu_snippet.repository.class%` to override the class of the repository

**Comment by Doum-Super** [comment]
Hello, How can i modify this parameter ? in config.yml ?

**Comment by Doum-Super** [comment]
i do this:
`sulu_snippet:
    repository:
        class: CitationLatine\Bundle\MainBundle\Repository\SnippetRepository`

i abtain this error:
Unrecognized option "repository" under "sulu_snippet"

**Comment by wachterjohannes** [comment]
you can add following line to you `parameters.yml`:

```
    sulu_snippet.repository.class: MyBundle\Repository\SnippetRepository
```

**Comment by danrot** [comment]
I think this issue is solved 😃
