### ISSUE TITLE
Error on translating external Links

### ISSUE THREAD

**Issue by tomsvogel** [sulu/sulu-standard#656]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.0.11
| Browser Version | each

#### Actual Behavior

Error on translate external Link

#### Expected Behavior

Success on translate external Link ;)

#### Steps to Reproduce

I use External link in my primary language (de) 
switched to en and create new page for en (bug occures on both options) 
tried to change the Title of the link and got exception

`request.CRITICAL: Uncaught PHP Exception Sulu\Component\Content\Exception\MandatoryPropertyException: "Property "url" in structure "default" is required but no value was given. Loaded from "/usr/share/nginx/site/app/Resources/pages/default.xml"" at /usr/share/nginx/site/vendor/sulu/sulu/src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php line 219 {"exception":"[object] (Sulu\\Component\\Content\\Exception\\MandatoryPropertyException(code: 0): Property \"url\" in structure \"default\" is required but no value was given. Loaded from \"/usr/share/nginx/site/app/Resources/pages/default.xml\" at /usr/share/nginx/site/vendor/sulu/sulu/src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php:219)"} []
[2016-03-31 09:05:21] security.DEBUG: Write SecurityContext in the session [] []`

**Comment by danrot** [comment]
I just tested this again, the bug doesn't occur to me anymore. Please reopen and deliver more details if that is not true for you.
