### ISSUE TITLE
Adding custom localization to webspace fails sulu:build

### ISSUE THREAD

**Issue by papablack** [sulu/sulu-standard#663]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | a3a25c6543c4c6872a45956dd1770895409be39a
| Browser Version | 49.0.2623.110

#### Actual Behavior

During build the console throws 

```
sulu_snippet.document.snippet_initializer
          [ ] snippet path:: /cmf/snippets
        sulu_core.webspace.document_manager.webspace_initializer
          [ ] homepage: /cmf/sulu_io/contents (en)


          [Symfony\Component\Debug\Exception\ContextErrorException]
          Notice: Undefined variable: homeType

```

when i add custom localization to the webspace

```
 <name>sulu.io</name>
    <key>sulu_io</key>

    <localizations>
        <localization language="en" default="true"/>
        <localization language="pl"/>
    </localizations>

(...)
```

#### Expected Behavior

I want it to build properly?

**Comment by wachterjohannes** [comment]
could you please run the command with the flag `-vvv` and post the additional informations? maybe also take a look into the log there could be some informations which is important to find out whats happen!

**Comment by danrot** [comment]
@papablack You are talking about the localization directly under the `webspace` tag, right? They are mandatory, and also the XSD says so. Or do you talk about the optional localizations under the `portal` tag?

**Comment by papablack** [comment]
@danrot The webspace tag.

**Comment by danrot** [comment]
@papablack Ok, then this is a misconfiguration. You have to define the locales for the webspace, since Sulu doesn't provide any defaults here. This is also part of the schema. The only thing confusing me here is the fact that you don't get a warning about a wrong configuration file, like I did when I tried that:

![image](https://cloud.githubusercontent.com/assets/405874/14460636/d4e67848-00be-11e6-8d5a-ddbba3d8b8be.png)

Can you maybe paste your entire webspace config? There seems something else to be wrong.

**Comment by papablack** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.0.xsd">

    <name>sulu.io</name>
    <key>sulu_io</key>

    <localizations>
        <localization language="en" default="true"/>
        <localization language="pl"/>
    </localizations>

    <theme>
        <key>default</key>
        <default-templates>
            <default-template type="page">default</default-template>
            <default-template type="homepage">overview</default-template>
        </default-templates>

        <error-templates>
            <error-template default="true">ClientWebsiteBundle:views:error.html.twig</error-template>
            <error-template code="404">ClientWebsiteBundle:views:error404.html.twig</error-template>
        </error-templates>
    </theme>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="en">Mainnavigation</title>
                    <title lang="pl">Nawigacja</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>Black Sulu</name>
            <key>black_sulu</key>
            <resource-locator>
                <strategy>tree</strategy>
            </resource-locator>

            <environments>
                <environment type="prod">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>
`

**Comment by papablack** [comment]
right now after I found the line throwing error and commented it out, once after it builded now build comes w/o error. It just printed out that $homeType variable is not set before printing. Now it's cool.

https://github.com/sulu/sulu/blob/1.2.0/src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php#L108

I'll keep watching this problem i'll try installing it anew when i finish transleting Admin into polish then i'll contact you to give you the translation it could be useful.

**Comment by danrot** [comment]
Is it possible that you were using an old version of Sulu? As you've mentioned it, I remembered that there was an error regarding this variable. Can you update and see if you still get the wrong error message?

And a polish translation would be super awesome 😃 Do you know how the translation works? There is a new section in the docs about that now: http://docs.sulu.io/en/latest/developer/contributing/adding-translations.html

**Comment by papablack** [comment]
oh thanks it will come in handy I was going to just dig with my mad analysis skills ;). Already have translated main admin file. I'm a Senior Symfony2 Developer here in Poland. Thanks for that link it will save A LOT of my time :)

**Comment by danrot** [comment]
So you were about to directly translate the files in `web/admin/translations`? Would have been lost with the next update 😉 We were already thinking about removing these files, since having built files in a repository is not nice, as you can see it is confusing, and leads to conflicts quite often. Created an issue for that: https://github.com/sulu/sulu-standard/issues/667

**Comment by papablack** [comment]
no i tried to overwrite translation files from app\Resources folder

**Comment by danrot** [comment]
ah, ok... well, would work, but might get confusing :-) Please make sure that you translate the files in https://github.com/sulu/sulu, also in every bundle :-)

**Comment by papablack** [comment]
yeah, I was just trying to get it working but only when i succeed i wanted
to contribute of course. I'm going to do this with proper pull request when
i'm done. Although for now i got only the AdminBundle translated.

______________________

Pozdrawiam, Jakub Pawlik / Best regards, James Pawlik


2016-04-13 13:30 GMT+02:00 Daniel Rotter <notifications@github.com>:

**Comment by danrot** [comment]
Cool 😃 Btw, can we agree on closing this issue?

**Comment by papablack** [comment]
aye aye sir.

**Comment by iBasit** [comment]
I get the same error using `composer create-project sulu/sulu-minimal my-project -n` command (obviously after I run `bin/adminconsole sulu:build dev` or `prod`)

**Comment by iBasit** [comment]
```php
 [Symfony\Component\Debug\Exception\ContextErrorException]                                                                         
          Catchable Fatal Error: Argument 1 passed to Twig_Function::__construct() must be an instance of string, string given, ca  
          lled in .../Sulu/Component/Webspace/Manager/Dumper/WebspaceCollectionDu  
          mper.php on line 26 and defined 
```

**Comment by danrot** [comment]
@iBasit Which version of twig do you have installed? There was a breaking change in a recent version, so that might be the reason. Can you try to update twig once more?

**Comment by iBasit** [comment]
```
        "twig/extensions": "~1.0",

**Comment by danrot** [comment]
@iBasit I don't think so, have just tested it, and it works perfectly fine... And I was talking about `twig/twig`:

This is what is installed on my machine: 
```
 ~/Temporary/my-project $ composer show twig/twig
name     : twig/twig
descrip. : Twig, the flexible, fast, and secure template language for PHP
keywords : templating
versions : * v2.2.0
type     : library
license  : BSD 3-clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
source   : [git] https://github.com/twigphp/Twig.git 29bb02dde09ff56291d30f7687eb8696918023af
dist     : [zip] https://api.github.com/repos/twigphp/Twig/zipball/29bb02dde09ff56291d30f7687eb8696918023af 29bb02dde09ff56291d30f7687eb8696918023af
names    : twig/twig

autoload
psr-0
Twig_ => lib/

requires
php ^7.0
symfony/polyfill-mbstring ~1.0

requires (dev)
psr/container ^1.0
symfony/debug ~2.7
symfony/phpunit-bridge ~3.2
```

**Comment by iBasit** [comment]
@danrot  I have tried another go with latest version 1.5.2, but unfortunately I'm still getting the same error. Following is the twig version and also PHP version installed.

```
name     : twig/twig
descrip. : Twig, the flexible, fast, and secure template language for PHP
keywords : templating
versions : * v2.2.0
type     : library
license  : BSD 3-clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
source   : [git] https://github.com/twigphp/Twig.git 29bb02dde09ff56291d30f7687eb8696918023af
dist     : [zip] https://api.github.com/repos/twigphp/Twig/zipball/29bb02dde09ff56291d30f7687eb8696918023af 29bb02dde09ff56291d30f7687eb8696918023af
names    : twig/twig

autoload
psr-0
Twig_ => lib/

requires
php ^7.0
symfony/polyfill-mbstring ~1.0

requires (dev)
psr/container ^1.0
symfony/debug ~2.7
symfony/phpunit-bridge ~3.2
```

PHP version
```
PHP 5.6.27 (cli) (built: Oct 24 2016 18:47:32) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

error
```
Fatal error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Twig_Function::__construct() must be an instance of string, string given, called in /Users/basit/projects/sulu-test/vendor/sulu/sulu/src/Sulu/Component/Webspace/Manager/Dumper/WebspaceCollectionDumper.php on line 26 and defined' in /Users/basit/projects/sulu-test/vendor/twig/twig/lib/Twig/Function.php on line 35
```

**Comment by iBasit** [comment]
@danrot found the problem. It is PHP version. If PHP version below 7.  Then you will have problem. Else it will work fine.

**Comment by iBasit** [comment]
after fixing php version I'm getting following error now from command line

```
sulu_core.webspace.document_manager.webspace_initializer
          [+] homepage: [overview] /cmf/sulu_im/contents (en)
        
                                                                     
          [Symfony\Component\Debug\Exception\FatalThrowableError]    
          Call to a member function getProperties() on null  
```

**Comment by danrot** [comment]
@iBasit So you are saying that you have PHP 5.6 installed? Then you should actually not get Twig 2 at all. Do you maybe have different PHP versions running on your webserver and on the terminal? That could cause conflicts like that.

**Comment by iBasit** [comment]
Ya I have upgraded to PHP 7 for sulu and it finally start running, but when I run the command line for dumping data. I still get the above error. 

I have check php -v, which is following from command line. 

```
PHP 7.0.12 (cli) (built: Oct 24 2016 18:49:11) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by danrot** [comment]
@iBasit I think whatever error you have is not related to this issue. Would you mind creating a slack account on our [website](http://sulu.io)? I think it is more efficient to help you out there.
