### ISSUE TITLE
Problem with user roles at demo.sulu.io

### ISSUE THREAD

**Issue by krewetka** [sulu/sulu-standard#666]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | current demo site
| Browser Version | Chrome 49.0.2623.110

#### Actual Behavior

I created user role called "basic user" and give only premissions to all operations under Webspaces->demo_sulu_io. I wanted user to have only access to main content edit, no contacts, settings etc.

I created user test/test with "basic user" usergroup and tried to login. I can access demo.sulu.io->homepage but not demo.sulu.io->content. 

I can see Internal error 500 for http://demo.sulu.io/admin/api/nodes?webspace=demo_sulu_io&language=en&fields=title,order&exclude-ghosts=false&exclude-shadows=false

#### Expected Behavior

Beeing able to access emo.sulu.io->content

#### Steps to Reproduce

Create user role with only this permissions. 
![image](https://cloud.githubusercontent.com/assets/207319/14422982/b81b6542-ffd9-11e5-932c-0c3babf200be.png)

Then assign it to some user and try to login and acess demo.sulu.io->content on http://demo.sulu.io

Don't know which exactly version of code demo site is using but it looks a bit different than what I downloaded from master. 

In my clean local version downloaded yesterday from git master it works fine but it's newer version than demo and with no content now. I guess some contenct from demo might be the problem.

**Comment by danrot** [comment]
You are right, that problem only occurs on the demo site... We will update it soonish, I assume that this is the cause of the problem, and not the data being contained in it. /cc @chirimoya

**Comment by krewetka** [comment]
@danrot thanks for the information. I'm glad that it's already fixed in the newest version,

**Comment by danrot** [comment]
@krewetka Demo is now updated, so this problem should be solved.
