### ISSUE TITLE
Remove built translations files

### ISSUE THREAD

**Issue by danrot** [sulu/sulu-standard#667]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0

#### Actual Behavior

Currently sulu-standard delivers the built translation files in the `web/admin/translations` folder,  which is obviously quite confusing, since potential contributors already tried to update these files. We cannot merge these changes, since they would be lost the next time we build our translations.

#### Expected Behavior

The translations should not be delivered with sulu-standard. Just removing them is easy, but the real question is how to build easily build them. There are different possibilities:

1. My suggestion would be to include them in the `.gitignore` file and add the `translations` builder to the `dev` and `prod` group of the `sulu:build` command. This way it would not make the installation harder, it would only take a few seconds more. However, @chirimoya raised the valid concern that people might not want to execute `sulu:build` on the production environment. People then would have to manually edit the `.gitignore` file for their project.

2. So the second solution would be like 1., but not adding the files to `.gitignore`, and we have to be careful when committing. (don't really like the solution, but I might be a bit biased based on my position 😊)

3. Same like solution 1., but people do not edit the `.gitignore` file, but instead run `app/console sulu:build translations` on the server. Would make the online going a little bit harder.

**Comment by danrot** [comment]
@webmozart I think that's especially of your interest, since it is related to https://github.com/sulu/sulu/issues/2078. But of course I would also like to hear the opinion of @chirimoya, @wachterjohannes and @dantleech

**Comment by dantleech** [comment]
Is there not a way to remove the "translation builder"?

- I can't see where you edit translations in the UI, why are they stored in the DB?
- If they can be edited, then do they need to be subsequently rebuilt?
- If they do need to be rebuilt, why don't we render the translations with a controller?

**Comment by danrot** [comment]
@dantleech I'd say it is another discussion. Of course, in the current state it does not really make sense to put them in the database, but the initial idea was that they are editable via the UI, it's just not implemented yet. But even if we remove them from the database, we still have to build them in some way, and that's what we need this command for (even if we just read the xlf files and translate them into the minified json version we need for the admin).

**Comment by danrot** [comment]
That was done in https://github.com/sulu/sulu/pull/2608
