### ISSUE TITLE
Search in documents of contacts (organisation, person)

### ISSUE THREAD

**Issue by connyzumtobel** [sulu/sulu-standard#670]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.1.10
| Browser Version | Browser name and version all

#### Actual Behavior

nothing happens
![screenshot 2016-04-14 13 20 03](https://cloud.githubusercontent.com/assets/14923924/14526463/b7b63dcc-0243-11e6-939b-3eadcbbda138.png)

#### Expected Behavior

to see search results ;-)

**Comment by danrot** [comment]
Closed with https://github.com/sulu/sulu/pull/2303
