### ISSUE TITLE
Exception starting sulu

### ISSUE THREAD

**Issue by marcosreiniertr** [sulu/sulu-standard#673]
Hello! I have just installed sulu, and all is rigth until I open it in my we browser. 
The error:
An exception occurred while executing 'SELECT w0_.title ........ 
SQLSTATE[42883]: Undefined function: 7 ERROR: **the operator does not exist: boolean = integer**
LINE 1: ... w1_ ON w1_.id = w2_.domain WHERE w0_.**all_domains = 1** OR (w1...
^
No operator matches the name and type of arguments. You may need to add explicit type conversions.
 500 Internal Server Error - DriverException 
...

**Comment by wachterjohannes** [comment]
good morning (: can you give us some more information about your environment? which database do you use? how you have installed sulu and which version you use?

ps: please use our issue-template the next time. this would answer at least a few of thus questions and we could categorize your issue better.

**Comment by wachterjohannes** [comment]
i have searched i a bit for this issue and it seems like that this happens with PostgreSQL. if you use this database we currently have some problems with it. /cc @dantleech can you give some more information about the compatibility with PostgreSQL?

**Comment by dantleech** [comment]
Seems indeed to be a Postgres error code. Sulu does not currently work with Postgres as per the above linked issue.

**Comment by marcosreiniertr** [comment]
I´m sorry for the lack of information. I installed sulu on windows + xamp 3.2.2 and PostgreSQL and yeap it was a problem with postgres interaction; it does not support "1" as a boolean value, but "TRUE". Thanks all
