### ISSUE TITLE
Some images have wrong viewport in file browser and website

### ISSUE THREAD

**Issue by tobias47n9e** [sulu/sulu-standard#674]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Development Version last updated 25.3.2016 (499dfc608d10f236f6cbfd550aec033b811abb4d)
| Browser Version | 50.0.2661.26 beta (64-bit)

#### Actual Behavior

Certain images in file-browser details-dialog have a wrong viewbox. Images with transparent background are also floating above the placeholder icon. 

The image with the wrong viewbox also has the wrong viewbox on the website, although the correct scaling-method is used.

![pasted image at 2016_04_20 15_10](https://cloud.githubusercontent.com/assets/6953323/14676153/8106b0b8-070c-11e6-8464-4914864cef2a.png)

#### Expected Behavior

Images should have the correct viewbox. Transparent images should be drawn on a canvas instead of the placeholder icon.

#### Steps to Reproduce

Upload test images. View them in the file-browser details-dialog.

Use the images on a website using this format declaration:

```
    <format>
        <name>50x50</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">50</parameter>
                    <parameter name="y">50</parameter>
                    <parameter name="mode">inset</parameter>
                </parameters>
            </command>
        </commands>
    </format>
```

![icons-02](https://cloud.githubusercontent.com/assets/6953323/14676048/1a5faebe-070c-11e6-8578-4d7b291cdd6c.png)
![icons-03](https://cloud.githubusercontent.com/assets/6953323/14676047/1a5f8204-070c-11e6-8ae2-d618f06ea376.png)
![icons-04](https://cloud.githubusercontent.com/assets/6953323/14676050/1a625024-070c-11e6-9505-e3b8bc73431d.png)
![icons-05](https://cloud.githubusercontent.com/assets/6953323/14676049/1a60f800-070c-11e6-87d4-705d3682cead.png)

**Comment by tobias47n9e** [comment]
These two images are larger. The square has the correct viewport in the admin interface and on the website. The portrait aspect ratio seems to cause the problems. It is cut off at the bottom and top both in the admin interface and the website.

![trophy](https://cloud.githubusercontent.com/assets/6953323/14782876/3c14c204-0aec-11e6-9b48-d9c511609462.png)
![trophy](https://cloud.githubusercontent.com/assets/6953323/14782879/46d2b926-0aec-11e6-8a37-d3f9c69af900.png)

**Comment by danrot** [comment]
@marcelmoosbrugger Please add the PR here.
