### ISSUE TITLE
language get in the routing in a wrong way

### ISSUE THREAD

**Issue by Kharestani** [sulu/sulu-standard#676]
Hi
Thanks for the hard work and this CMS. I have WAMP on my system and I run my web applications on that so when I have a symfony project named "MyProject" the address will be : `<http://localhost/MyProject/web/app_dev.php>` in the browser. The problem is when I try to see my first sulu project named "MySulu" and I enter `<http://localhost/MySulu/web/app_dev.php>` to the browser, it automatically add "/en" to the rout but in a wrong place like this: `<http://localhost/en/MySulu/web/app_dev.ph>` which I guess must be like this: `<http://localhost/MySulu/web/app_dev.ph/en>`

Thanks again

**Comment by wachterjohannes** [comment]
hmm i have no experiences with wamp (maybe @alexander-schranz can add his thoughts) are you able to add a "vhost" to your web-directory? can you post you webspace configuration and which version did you use.

ps: please use our issue template because there is at least clear that you should add your version (:

**Comment by alexander-schranz** [comment]
Hello @Kharestani,

Sulu have no environment specific php files `app_dev.php` or `app.php`. Their exists the `website.php` (for the website) and `admin.php` (for the backend) the Environment (dev) you need to set in your VHOST (`SYMFONY_ENV`) or directly in the PHP files. 

I would recommend you to create a VHOST. Example for the VHOST you can find them here: http://docs.sulu.io/en/latest/book/getting-started/vhost.html#apache-2-2. The vhost need to web folder as root target. 

A tutorial for wamp I found here https://john-dugan.com/wamp-vhost-setup/. When you created your vhost and the local domain point to your pc. You need to add the domain to your webspace (`app/Resources/webspaces/*.xml) to the portal url in the correct environment. Example can be found here: http://docs.sulu.io/en/latest/book/creating-a-basic-website/setup-a-webspace.html.

**Comment by Kharestani** [comment]
Hi
Thanks to @wachterjohannes and really sorry for not using the template.
and real thanks to @alexander-schranz  for the thorough explanation and step by step solution for this.

You all Rock!
