### ISSUE TITLE
Search in "ansprechpersonen" of contacts (organisation, person)

### ISSUE THREAD

**Issue by connyzumtobel** [sulu/sulu-standard#678]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.1.10
| Browser Version | All

#### Actual Behavior

nothing (seems to be the same behavior as #670)

#### Expected Behavior

to see search results

<img width="998" alt="screen shot 2016-04-25 at 16 43 58" src="https://cloud.githubusercontent.com/assets/14923924/14788157/009a18e4-0b07-11e6-9f78-88bff769413c.png">

**Comment by wachterjohannes** [comment]
the hotfix for #670 is not released currently you can use dev-master where the fix is included for 1.2 @chirimoya should we also include this into 1.1 series?

**Comment by wachterjohannes** [comment]
i have checked that and i was wrong yesterday (: i will create a PR for this today
