### ISSUE TITLE
Media Navigation Bar is visible on content page.

### ISSUE THREAD

**Issue by dominikmatt** [sulu/sulu-standard#680]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0
| Browser Version | Chrome 50

#### Actual Behavior

Media Navigation Bar is visible on content-page.

#### Steps to Reproduce

1. Navigate to a any content-page
2. then navigate to the Media-Module
3. press the history back button
4. now the Media Navigation bar is visible in the conten-page

**Comment by chirimoya** [comment]
![bildschirmfoto 2016-04-29 um 09 16 37](https://cloud.githubusercontent.com/assets/627313/14910129/1cd91726-0deb-11e6-96f6-ff0714b9f772.png)
