### ISSUE TITLE
Set priority to a Portal?

### ISSUE THREAD

**Issue by fvera87** [sulu/sulu-standard#683]
| Q | A
| --- | ---
| Bug? | yes?
| New Feature? | no
| Sulu Version | 1.2.0
| Browser Version | Irrelevant

#### Actual Behavior

How does Sulu behave at the moment? 

Maybe it's not a bug, but I just can't find how to solve it :-) 
I have two portals that share the "beginning" of the url: 
Portal 1: example.com/{language}_{country}/foo
and Portal 2: example.com/{language}_{country}/landingpage/foo

Let's assume that I need to access to the contents under example.com/de_DE/landingpage/contact.

Here I got a 404 error. There is still some "magic" under Sulu for me, so I don't really know how to change that, but looking around with xdebug and after several hours of debugging I found out that in  the class WebsiteRequestProcessor, in the process function, you sort the possible "matches" of portals that contains an url that can be associated with the request in base of the portal priority.

The problem is that I can't see how to change that priority, I always have the different PortalInformation objects for those portals bue the priority is a constant, so as they always have the same priority, the order never changes, and they get the first and more "general" example (example.com/{language}_{country}). 

Is something that I'm doing wrong? Is something that is missing? 

Thank you guys for the good work, and sorry if this is just my fault :-) 

#### Expected Behavior

Have some way to set the priority of the portal within the webspace xml definition file.

#### Steps to Reproduce

Described above.

**Comment by danrot** [comment]
Can you try to update to 1.2.1? I've added [some lines to the sorting in the WebsiteRequestProcessor](https://github.com/sulu/sulu/blob/1.2.1/src/Sulu/Component/Webspace/Analyzer/Attributes/WebsiteRequestProcessor.php#L83).

From what you are saying here it looks to me as if the wrong portal is used. We've had a similar bug with another setup, and it was solved by saying that the portal with the longest URL "wins" in case the priority is the same. However, mind that you are blocking the `/landingpage` resourcelocator for usage in the other portal then.

If you issue is solved with an update, I would be happy if you close this issue :-)

**Comment by fvera87** [comment]
Perfect, that solved the problem :D 

Regards and congratulations for the good work ;)
