### ISSUE TITLE
SULU needs to be translated to all languages let's make it happen!

### ISSUE THREAD

**Issue by Kharestani** [sulu/sulu-standard#685]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | all

#### Proposal
SULU is getting stronger every day so I propose you add this project on the `<https://crowdin.com/>` or other similar tools and allow people to translate it to variuos languages.

**Comment by danrot** [comment]
I think you've closed the issue because there is already the similar one https://github.com/sulu/sulu/issues/2149, right?

**Comment by Kharestani** [comment]
yes
Thank you
