### ISSUE TITLE
Can we install the cms as a bundle in a existing project ? 

### ISSUE THREAD

**Issue by speeeeeed2006** [sulu/sulu-standard#687]
Hello it' was maybe a simple question but can I kno if I can add Sulu to an existing project I developping now. I use symfony 2.8.4 and I'm looking for a content manager other than Sonata. 
If you maybe also know one that can help me I will be happy to try it. 
Thanks

**Comment by wachterjohannes** [comment]
easy answer: sulu can be included in existing projects. you can take a look into the code of sulu-standard (config, kernel, routing).

but if you use (like nearly all symfony application) a single kernel application it could be quite hard to merge sulus kernels. But you could try to introduce the two kernel architecture of sulu and include your app into website-kernel (and / or  admin-kernel) depending on the type of your application. you can request the access to our slack channel here http://sulu.io/en#questions

**Comment by danrot** [comment]
I guess this answer is answered well enough, closing the issue. Please reopen or just comment in case something is not clear yet.
