### ISSUE TITLE
SEO alternate Links not rendered on Startpage 

### ISSUE THREAD

**Issue by dominikmatt** [sulu/sulu-standard#688]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.0

#### Actual Behavior

No alternate links on startpage.

**Comment by danrot** [comment]
Seems to be fixed: 
![image](https://cloud.githubusercontent.com/assets/405874/15709097/1133d596-2803-11e6-9402-d168d534f15e.png)

**Comment by alexander-schranz** [comment]
@dominikmatt this was fixed in 1.2.2
