### ISSUE TITLE
Issue when upgrading from 1.1 to 1.2

### ISSUE THREAD

**Issue by ollietb** [sulu/sulu-standard#689]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.1
| Browser Version | N/A

#### Actual Behavior

When upgrading and running the doctrine:schema:update command like in the UPGRADE.md, I get an error regarding foreign key contraints. This happens on my local environment as well as the live instance of our site. The error is 
```
[Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'ALTER TABLE se_users CHANGE idContacts idContacts INT NOT NULL':
  SQLSTATE[HY000]: General error: 1832 Cannot change column 'idContacts': used in a foreign key constraint 'FK_B10AC28E60E33F28'
```
There are no users with `se_user.idContacts IS NULL`

#### Expected Behavior

The database to update without an error

#### Steps to Reproduce

Have a working site with 1.1. Upgrade to 1.2 and run the command `app/console doctrine:schema:update --force`

#### Possible Solutions

Use migrations instead of forcing the schema?
I had to manually remove the foreign key and run the schema update command. Maybe this should be documented in the upgrade notes?

**Comment by alexander-schranz** [comment]
Hello @ollietb,

seems like you created in your project users without contacts. 
Mention in the Upgrade.md (https://github.com/sulu/sulu/blob/develop/UPGRADE.md#contact-entity-is-required-for-user)  you need to make sure your users have a contact entity.

**Comment by ollietb** [comment]
@alexander-schranz yes I ran that query and there were no results returned

**Comment by ollietb** [comment]
```
php app/console doctrine:query:sql "SELECT * FROM se_users WHERE se_user                                   s.idContacts IS NULL" --env=prod
array(0) {
}
```

**Comment by alexander-schranz** [comment]
Ok thats strange maybe a contact entity not exists try:

```
SELECT * FROM se_users u
LEFT JOIN co_contacts c ON
    u.idContacts = c.id
 WHERE c.id IS NULL 
```

**Comment by ollietb** [comment]
@alexander-schranz it returns an empty result
```
php app/console doctrine:query:sql "SELECT * FROM se_users u LEFT JOIN co_contacts c ON u.idContacts = c.id WHERE c.id IS NULL " --env=prod
array(0) {
}
```

**Comment by ollietb** [comment]
@alexander-schranz I thought it must be some kind of data problem with my local environment but when I ran it on our staging environment exactly the same thing happened

**Comment by alexander-schranz** [comment]
@ollietb which DB and version?

**Comment by ollietb** [comment]
@alexander-schranz MySQL 5.7.10

**Comment by wachterjohannes** [comment]
do you have tried to update your database with foreignkey check false?

**Comment by wachterjohannes** [comment]
http://stackoverflow.com/a/35578968/5357967

**Comment by ollietb** [comment]
Yeah I kind of did it that way in the end by deleting the constraint and running the update again

**Comment by chirimoya** [comment]
We should use doctrine migration in future ... https://github.com/sulu/sulu/issues/2072

**Comment by wachterjohannes** [comment]
@ollietb so it has worked for you now?

**Comment by ollietb** [comment]
@wachterjohannes it worked, but not according to the documentation. I had to remove the constraint before running the query. I could do a PR for the upgrades notes if you like? But maybe no one else has the same trouble as me. OK to close if you don't want to persue.

**Comment by wachterjohannes** [comment]
hmm it seems that nobody has the same trouble. maybe you could add some notes here onlyfor documentation.
