### ISSUE TITLE
Removed content can't be accessed by SearchBundle

### ISSUE THREAD

**Issue by ollietb** [sulu/sulu-standard#690]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.1
| Browser Version | n/a

#### Actual Behavior

When updating from 1.1 to 1.2.1 I ran the `php app/console massive:search:reindex --env=prod -vvv` command and I'm getting this error
```
  [InvalidArgumentException]
  The block type "paralax_image" has not been registered. Known block types are: [content_text_block, content_with_columns, special_image]
```
I've traced the block type name to an old template which has been changed, and the page in the CMS has been deleted so I don't know how to fix the error. I've tried browsing the content through the phpcr shell and that block isn't in there anywhere.

#### Expected Behavior

The index to be updated without an error

#### Steps to Reproduce

I imagine it's when a block is created and then renamed, but I'm not sure why it's still failing even when the page is deleted - maybe it's saved in the versioning?

#### Possible Solutions

Ignore errors during indexing?

**Comment by danrot** [comment]
Wouldn't it solve the problem to simply purge the index with the `massive:search:purge` command before reindexing? Usually pages should be deleted when also from the index, is it possible that something went wrong there?

**Comment by ollietb** [comment]
@danrot I tried purging the index but it still gives me the same error

```
[ec2-user@ip-10-0-0-xx eventstag]$ sudo php app/console massive:search:purge --env=prod
Specify the option: --index=<index_name> where <index_name> is one of the following:

  contact
  page_eventstag
[ec2-user@ip-10-0-0-xx eventstag]$ sudo php app/console massive:search:purge --env=prod --index=page_eventstag
Are you sure you want to purge index "page_eventstag"? y
[ec2-user@ip-10-0-0-xx eventstag]$ sudo php app/console massive:search:reindex --env=prod
provider "doctrine_orm"

-- reindexing "4" instances of "Sulu\Bundle\ContactBundle\Entity\Contact"

 4/4 [============================] 100% Mem: 42,341,408b

-- reindexing "0" instances of "Sulu\Bundle\ContactBundle\Entity\Account"

    0 [>---------------------------]

-- reindexing "101" instances of "Sulu\Bundle\MediaBundle\Entity\FileVersionMeta"

 101/101 [============================] 100% Mem: 45,360,624b

-- reindexing "0" instances of "Sulu\Bundle\CategoryBundle\Entity\CategoryTranslation"

    0 [>---------------------------]

provider "sulu_structure"

-- reindexing "11" instances of "Sulu\Bundle\ContentBundle\Document\PageDocument"

  5/11 [============>---------------]  45% Mem: 57,955,584b

  [Exception]
  Error encountered when trying to determine value from object "Sulu\Bundle\ContentBundle\Document\PageDocument"



  [RuntimeException]
  Error encountered when evaluating expression "object.getStructure().content_blocks.getValue()"



  [InvalidArgumentException]
  The block type "paralax_image" has not been registered. Known block types are: [content_text_block, content_with_columns, speci
  al_image]

```

**Comment by danrot** [comment]
TBH it looks to me like there is still a page existing with the old block type... At least that's the only way I am able to reconstruct this on my machine. Can you maybe check the data using the [PHPCR Shell](http://phpcr.readthedocs.io/en/latest/phpcr-shell/) and see if there is still the `paralax_image` value standing in some field named after the schema `i18n:[language]-blocks-type#[number-of-block]`?

**Comment by ollietb** [comment]
OK, I've done a complete dump of all the nodes and there are some pages in there which were deleted through the UI a long time ago. It's possible that they have been added to the tree through a failed import when we were trying to get that working a couple of months ago. Thanks for your help.
