### ISSUE TITLE
media_selection not sorted correctly in Sulu Admin

### ISSUE THREAD

**Issue by dominikmatt** [sulu/sulu-standard#694]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.2
| Browser Version | Chrome 50

#### Actual Behavior

After reloading the Content-Page the media_selection Items not sorted correctly.
I get the correct sort on the Frontendpage.

#### Steps to Reproduce

**Setup:**
```
<property name="header_image" type="media_selection">
    <meta>
        <title lang="de">Header Bild</title>
        <title lang="en">Header Image</title>
    </meta>

    <tag name="sulu.search.field" index="false"/>
</property>
```

1. Add any Items
2. Sort them 
3. Make a browser reload or enter the page again

**after saving**
<img width="880" alt="bildschirmfoto 2016-05-11 um 15 16 32" src="https://cloud.githubusercontent.com/assets/3023954/15182231/c9673dac-178b-11e6-89fb-685d55491a82.png">

**after reloading**
<img width="850" alt="bildschirmfoto 2016-05-11 um 15 16 50" src="https://cloud.githubusercontent.com/assets/3023954/15182236/cd78d3f6-178b-11e6-81df-49d6cdcabf30.png">

**Comment by danrot** [comment]
Fixed with sulu/sulu#2440
