### ISSUE TITLE
SULU contact bundle and registration and user entity and other things!

### ISSUE THREAD

**Issue by Kharestani** [sulu/sulu-standard#699]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | develop

I know it is a long post please be patient!

I want to add user registration functionality to my sulu system, I have 2 choices :
1. use one of strong user bundles around the web like friends of symfony user bundle.
2. use sulu contact bundle

in the first solution the problem would be multiple user entities and that would be a problem in future for sure! on the second solution the problem will appear in the development process cause sulu contact bundle is not that strong yet and can not work with other useful bundles from FOS or Sonata project or etc or maybe I am wrong please help.

Also there is a problem with both of these choices; I plan to run multiple websites and even android apps on multiple webspaces sharing one sulu core but the contacts are shared between webspaces and there is a chance if one of users register on one of these webspaces through on of these websites then he could not register on other websites because when he tries to register he will see that his email is already registered! and of course he does not know these websites use one core.

I can add a parameter to user entity to indicate the webspace which user registered in. and restrict the admin login page to allow only admin roles and stop regular users getting in the admin panel. then I need to synchronize contact entity to be able to work with other strong bundles which are around and after that the challenge is started to make everything working like sulu structure with REST API and so on!

It does seems a lot of work to do! but I think you sulu people should separate sulu bundles in different repositories on GitHub to make it more developer friendly. in the current system it is too big and complicated!

Oh I talked and talked and talked! Now any idea what should I DO?

**Comment by alexander-schranz** [comment]
Hi @Kharestani,

I created a bundle for this  https://github.com/alexander-schranz/sulu-website-user-bundle. You can use it or have a look at it to create your own one.

**Comment by Kharestani** [comment]
Hi @alexander-schranz 

You rock man! I will check it and get back to you.

**Comment by wachterjohannes** [comment]
the bundle from @alexander-schranz is quite good so we can close this issue. if you have any other related issues you can reopen it.

**Comment by Kharestani** [comment]
ok @alexander-schranz awesome bundle does help but there is a problem with multiple webspace!
the contact entity does not contain information about user webspace and when a user register in one webspace it is accessible from other webspaces as well and that is not good because the beautiful sulu tries to make multiple apps and websites to run under a shared roof so ... we need to do something  I ask you @wachterjohannes to please reopen the issue to find a solution for this.

**Comment by Kharestani** [comment]
I propose `Contat spaces` in that way any webspace can be configured to use one of these `contact spaces` and multiple webspaces can share one contact space.

**Comment by wachterjohannes** [comment]
i think that should be possible with different roles for each webspace. because sulu checks the systems of the roles and therefor this should work @alexander-schranz correct me if i am wrong.

**Comment by alexander-schranz** [comment]
@Kharestani @wachterjohannes thats right you can have different roles for webspace A and webspace B. Think you need to configure the security.yml which role can access which routes. The only restriction is that the email and username is unique so you can not register on webspace A when you are registered on webspace B with the same mail address. 

There are 2 possibly solutions for this: 

1. You overwrite the User.orm.xml that the email address is not longer unique.
2. You create a cross registration (e.g. Register with your Shop account) This is something what is also on my roadmap (https://github.com/alexander-schranz/sulu-website-user-bundle/issues/14)

**Comment by wachterjohannes** [comment]
@Kharestani is that enough for you?

**Comment by Kharestani** [comment]
Brilliant! I think that will work for me and what I need but I think in future sulu should do this to make it more flexible.
thanks alot to @alexander-schranz for the solution and to @wachterjohannes for all of this.
