### ISSUE TITLE
Bug missing pagination contact list of customer

### ISSUE THREAD

**Issue by connyzumtobel** [sulu/sulu-standard#702]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.2 |
| Browser Version | Chrome Version 50.0.2661.102 (64-bit) |
#### Actual Behavior

If another user has opened the same customer Sulu doesn't shows the pagination of the contact list (screen)
#### Expected Behavior

See Pagination

![screenshot 2016-05-20 12 15 17](https://cloud.githubusercontent.com/assets/14923924/15425147/b8fec262-1e86-11e6-80ad-751acdab8316.png)

**Comment by chirimoya** [comment]
https://github.com/sulu/sulu/pull/2320
