### ISSUE TITLE
webspaces, pages and snippets are ignored in .gitignore, is there a rule for them?

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu-standard#705]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.2
| Browser Version | Not Related

#### Actual Behavior

How does Sulu behave at the moment? 

webspaces, pages and snippets are ignored in .gitignore

#### Question

If I want to add it to my git repo should they be situated somewhere specifically rather than app/Resources, or they should be named .dist and then copied everytime a pull and push is done?

**Comment by alexander-schranz** [comment]
Hi @piratadelfuturo,

when we create a new sulu project we remove the lines (https://github.com/sulu/sulu-standard/blob/develop/.gitignore#L31-44) from the .gitignore files.

**Comment by alexander-schranz** [comment]
@sulu/core-team maybe this should be added to the docs?

**Comment by wachterjohannes** [comment]
we currently working on a cleaner installation example which should replace sulu-standard. then we recommend not to pull from the installation repository. therefor this issue should be obsolet soon.
