### ISSUE TITLE
Home page cannot be published in new language

### ISSUE THREAD

**Issue by papablack** [sulu/sulu-standard#709]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 7c751e56c1750b39ae704da570c0268aceeb1864

#### Actual Behavior

I'm making first website in sulu its Polish / English. I'm also testing polish translations I mentioned before. The problem is that I have working engilsh homepage and polish homepage (which should be default) just cannot let me publish itself. Even if i try to change something and it let's me publish it it's still yellow and the button is disabled.

#### Expected Behavior

I expect that my homepage can get updated.

#### Steps to Reproduce

Create new language for the site and make a hompage in it.

My webspace file:

````
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.0.xsd">

    <name>uplink</name>
    <key>uplink_site</key>

    <localizations>
        <localization language="pl" default="true"/>
        <localization language="en"/>
    </localizations>

    <theme>
        <key>uplink</key>
        <default-templates>
            <default-template type="page">default</default-template>
            <default-template type="homepage">overview</default-template>
        </default-templates>

        <error-templates>
            <error-template default="true">ClientWebsiteBundle:views:error.html.twig</error-template>
            <error-template code="404">ClientWebsiteBundle:views:error404.html.twig</error-template>
        </error-templates>
    </theme>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="pl">Nawigacja</title>
                    <title lang="en">Main navigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>uplink</name>
            <key>uplink_portal</key>
            <resource-locator>
                <strategy>tree</strategy>
            </resource-locator>

            <environments>
                <environment type="prod">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url>{host}/{localization}</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>
````

**Comment by wachterjohannes** [comment]
the homepage has to be created by the command `sulu:document:initialize` also when you add a locale after initializing rerun the command it will append the needed nodes for you. did this help of misunderstood something?

**Comment by papablack** [comment]
Yes. Thank you. That helped. But now i have a problem. After I build sulu its ok for some time then at some moment my server freezes during browsing/saving content in admin then it breaks FontAwesome from husky from adminbundle. The assets are installed well. Here is the screenshot:

![suluicons](https://cloud.githubusercontent.com/assets/7440204/15909234/a98a9fd8-2dc5-11e6-9042-8428a623bbf7.png)

**Comment by papablack** [comment]
Ok guys fixing cache few times helped. Something must've locked those font files for a while. We can close this topic now.
