### ISSUE TITLE
Search in Collections

### ISSUE THREAD

**Issue by pjeroen** [sulu/sulu-standard#711]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.2.1 |
| Browser Version | All (Chrome, Safari) |
#### Actual Behavior

On smaller displays the search field within the collections is too small to place the cursor inside.
#### Expected Behavior

It would be good if a user could place the cursor in the search field.
#### Steps to Reproduce

![bildschirmfoto 2016-06-10 um 13 07 13](https://cloud.githubusercontent.com/assets/513131/15962689/2c8970b0-2f0d-11e6-873d-f3d579a0bc03.png)

**Comment by danrot** [comment]
Since the redesign of the media section there is no too small search field anymore, so I am closing this issue.
