### ISSUE TITLE
Assets area twice available

### ISSUE THREAD

**Issue by pjeroen** [sulu/sulu-standard#712]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.1
| Browser Version | All (Safari)

#### Actual Behavior

A user granted only access for the asset area will see the asset area twice.

#### Expected Behavior

The user should see the asset area only once.

#### Steps to Reproduce

![screen shot 2016-06-10 at 13 21 06](https://cloud.githubusercontent.com/assets/513131/15962895/6f7c0b02-2f0e-11e6-9f04-fb23614c0e83.png)
![screen shot 2016-06-10 at 13 21 44](https://cloud.githubusercontent.com/assets/513131/15962899/7575642c-2f0e-11e6-9ece-51d694108feb.png)

**Comment by danrot** [comment]
Fixed in #2390
