### ISSUE TITLE
Assets install of clientbundle

### ISSUE THREAD

**Issue by papablack** [sulu/sulu-standard#716]
| Bug? | no
| Sulu Version | 8e46f52569f9a0833961480f47348bd49d774e51

Gentlemen, i propose moving ClientWebsiteBundle from WebsiteKernel to AbstractKernel. Assets:install cannot find bundles from WebsiteKernel everything that needs assets should be in AbstractKernel. I wanted to make a pull request but how the hell do i push my branch to your repo?

**Comment by wachterjohannes** [comment]
you have to create a fork in your account. there you push the branch and you can create a PR on our repository.

Helpfull links:

* https://help.github.com/articles/fork-a-repo/
* https://help.github.com/articles/using-pull-requests/

**Comment by alexander-schranz** [comment]
To install the assets for the website kernel you need to run the `app/webconsole assets:install`.

**Comment by papablack** [comment]
oh. thanks. Is there any document holding this sulu specific commands in one place?

**Comment by alexander-schranz** [comment]
@papablack website and admin have its own Kernel. so they have also its own console. If you are on the website its `webconsole` if you are on the admin its `console` (in the future its `adminconsole` to avoid problems like this)

**Comment by wachterjohannes** [comment]
can this be closed?

**Comment by danrot** [comment]
Since there has been no answer for over two weeks I am closing this.
