### ISSUE TITLE
The requested URL /en/website.php was not found on this server

### ISSUE THREAD

**Issue by swanand09** [sulu/sulu-standard#717]
I am just making my first installation of sulu based on http://docs.sulu.io/en/latest/book/getting-started/setup.html and I ended up with a 404 error while accessing website.php which is being redirected to http://mywebproj/en/website.php

Can anyone plz clarify about this issue? Thanks in advance :)

**Comment by wachterjohannes** [comment]
@swanand09 i think that has to be a problem with your vhost configuration have you used the example from the docs? http://docs.sulu.io/en/latest/book/getting-started/vhost.html

For easier communication for such problems please use our slack-channel. you can get access from our website http://sulu.io/en#questions

**Comment by swanand09** [comment]
@wachterjohannes I have done exactly what is explained here( http://docs.sulu.io/en/latest/book/getting-started/vhost.html) but with the path of my project folder

**Comment by wachterjohannes** [comment]
do you try to access `blabla.lo/website.php`? because then sulu tries to find a page with the path `/website`. which is not created (i think) so you can omit it and everything should work fine. (the `website.php` file will be called internally by apache).

**Comment by swanand09** [comment]
yep it redirects me to blabla.lo/en/website.php

**Comment by wachterjohannes** [comment]
and if you try to access `blabla.lo` (without website.php)?

**Comment by swanand09** [comment]
it redirects me to blabla.lo/en/website.php

**Comment by wachterjohannes** [comment]
do you have installed and enabled the `mod_rewrite` module?

**Comment by swanand09** [comment]
thanks for this. I have enabled mod_rewrite and now it tells me: "[2/2] NotFoundHttpException: No route found for "GET /en/website.php""

**Comment by swanand09** [comment]
sorry blabla.lo redirects properly to blabla.lo/en with the frontend. Thanks again.

**Comment by swanand09** [comment]
and i can access the admin too. Nice!!

**Comment by wachterjohannes** [comment]
@swanand09 no problem (:
