### ISSUE TITLE
Sulu Doc doesn't mention all sulu_content_path arguments

### ISSUE THREAD

**Issue by thgie** [sulu/sulu-standard#720]
http://docs.sulu.io/en/latest/reference/twig-extensions/functions/sulu_content_path.html

Needs to mention `getContentPath($route, $webspaceKey = null, $locale = null, $domain = null, $scheme = null)`

I had a problem in which the twig containing the function call threw and error because the locale was missing due to rendering as esi.

**Comment by danrot** [comment]
Transferred the issue to the  [sulu-docs repository](https://github.com/sulu/sulu-docs/issues/235)
