### ISSUE TITLE
Console permissions: won't start on fresh install

### ISSUE THREAD

**Issue by SecondeJK** [sulu/sulu-standard#721]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | No
| Sulu Version | 57ec624a0b109ca91ee54b0aa35411f087b0331 (live - master 12/07/2016)
| Browser Version | N/A CLI

#### Actual Behavior

No console commands can be run after following the installation guide: Symfony 'RuntimeException' error  - Unable to create the cache directory (/cache/admin/).
This is after following permission changes on the command line (for OS X).

#### Expected Behavior

Once console commands are used, they should start working.

#### Steps to Reproduce

MacOS X: 10.11.5 [El Capitaine]
Git fetched Sulu
Run Composer - installed dependencies
Follow instructions as per getting-started/setup.html in docs
Altered templates, altered webspaces xml config 
Can't build prod or run console because cache problem with permissions.

This is _right out of the box_ on OSX using the documentation, so it's pretty disappointing.

**Comment by danrot** [comment]
That's probably also related to https://github.com/sulu/sulu/issues/2567... Don't know currently what's the real issue here, because it is working for me. I'll try to find some time today to analyze that.

**Comment by SecondeJK** [comment]
A sudo once on the console got it working, and it didn't complain about permissions again...it didn't look like it was paying attention to chmod. And this was with umask forced into the kernel as well, which it wasn't interested in somehow. Must be a macos quirk?

**Comment by danrot** [comment]
Well, we are also working on MacOS, so that can't be the reason... What were the permissions of the problematic folders? Maybe the problem was that the permissions were not set correctly after what you described in https://github.com/sulu/sulu-docs/issues/236?

**Comment by danrot** [comment]
@SecondeJK If I got you right the problem disappeared, so I am closing this issue.
