### ISSUE TITLE
I can't acces to session from template twig

### ISSUE THREAD

**Issue by Yoann-TYT** [sulu/sulu-standard#724]
Perhaps this problem is caused by my environnement, but I can't acces to my session from my template.

When I add

`{{dump(app.session)}}`

I got "null" response...

Is it normal on sulu ? Or you think that I have a problem in my configuration ?

Thanks !

Yoann

**Comment by alexander-schranz** [comment]
On a default installation on the website no session is started. Also you should keep in mind that all pages are response default as `public` and will be cached. 

If you are on a page template I recommend to keep the page cache and use an ESI (`render_esi`). In the esi controller you could start or access the session and set its response to private (`$response->setPrivate();`) . More about esi's in symfony http://symfony.com/doc/current/book/http_cache.html#using-esi-in-symfony.

**Comment by alexander-schranz** [comment]
@Yoann-TYT Maybe the session is not started else I cant help you because on my installation it works without problem also by accessing it directly in twig, but I would not recommend you to pass the whole session to twig, I would just pass the parameters so your template can be reuse. And pls use the github issue template next time!

```php
if (!$request->getSession()->isStarted()) {
    $request->getSession()->start();
}
```

**Comment by Yoann-TYT** [comment]
Trank you Alexander ;-)
I will use the github issue template next time ! 
And for my problem, I think it's a configuration problem... I tell you if I solve it. ( We can close this ticket if you want ! )

**Comment by alexander-schranz** [comment]
Ok thx let us know how you solved it.
