### ISSUE TITLE
Sulu not Connecting 

### ISSUE THREAD

**Issue by alramahy** [sulu/sulu-standard#734]
Hi everybody, i followed the steps to instal Sulu on Vagrant on this site 
https://www.sitepoint.com/?p=118527&preview=1&_ppp=5c599b0d88

and at the Point to connect to the DB it throw me this Error

 [Doctrine\DBAL\DBALException]                                                 
  The given 'driver' Homestead is unknown, Doctrine currently supports only the following drivers: pdo_mysql, pdo_sql
  ite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_sqlsrv, mysqli, drizzle_pdo_mysql, sqlanywhere, sqlsrv

Probably there is someone who know the mistake an can help me 

best regards

**Comment by alexander-schranz** [comment]
Hello @alramahy,

please use the Issue template next time.

What is inside your `app/config/parameters.yml` file there should be something like:

```
    database_driver:   pdo_mysql
```

I think `homestead` is your database_name and not driver. So you need to fix the configurations in your `app/config/parameters.yml`.

**Comment by danrot** [comment]
@alramahy I assume that this issue should be solved with these instructions. Please reopen the ticket if there are still some issues left.
