### ISSUE TITLE
[feature request] default navigation context and automatically add new sites

### ISSUE THREAD

**Issue by thgie** [sulu/sulu-standard#736]
A client of ours forgets to add a new content page to a navigation context and then complains why it doesn't show up. It would be great to be able to define a default context and have the option to add new content automatically to it.

**Comment by wachterjohannes** [comment]
we also thought about that and it would be quite easy todo. @chirimoya @danrot i think we should add it to 1.4! what do you think?

**Comment by wachterjohannes** [comment]
https://github.com/sulu/sulu/issues/422

**Comment by danrot** [comment]
I'd say we leave it in that milestone for now, and see if we have time to implement that.

**Comment by danrot** [comment]
Going to close this one, as there is already sulu/sulu#422
