### ISSUE TITLE
Edge: Edit Collection menu doesn't behave all the time

### ISSUE THREAD

**Issue by thgie** [sulu/sulu-standard#737]
| Bug? | yes
| Sulu Version | 1.2.6
| Browser Version | IE Edge

#### Actual Behavior

When I click on the Edit Collection button the menu open. But the two items within, Edit and Delete, are not clickable. When I start to shake the mouse pointer and move out of the menü and into the button sometimes the hand cursor apears and I can click the menu items.

Edgy ... lol

**Comment by wachterjohannes** [comment]
@thgie we have fixed that in the newest HOTFIX release of 1.2. I will close this issue but if you have problems also with the newest HOTFIX please reopen this issue (:
