### ISSUE TITLE
Permission issue in media

### ISSUE THREAD

**Issue by afroewis** [sulu/sulu-standard#739]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.2 (did not try on latest version)

There is an issue with locale permissions in the media bundle. I have a user that has all permissions in the `fr` locale (and only in this locale). If I click on "assets" in the backend (to see the media collections), the following error message is displayed: `Operation forbidden The available permissions are not sufficient for this operation`.  

Changing the locale in the upper right corner to `fr` does not work. I can't see, let alone upload, any media files. 

After I change the backend **language** in the bottom left corner to `fr`, everything works fine. 

#### Some technical info

This request is made if I log in with my `fr` admin: `http://daswerk.lo/admin/api/collections?sortBy=title&page=1&limit=20`. This returns a 403. If I add `&locale=fr`, the request is successful. 

#### Actual Behavior

It's not possible to change the locale with the select in the upper right corner. I have to change the backend language with the select in the bottom left corner to use the media section of the backend. 

#### Expected Behavior

The select in the upper right corner should work. After I change the locale to `fr`, it should display the media files. 

#### Steps to Reproduce

1. Create a user that has all permissions for a specific locale which is not the default locale
2. Log in with that user and click on "assets" in the backend
3. An error message is displayed and you can't change the locale with the select in the upper right corner. 

I guess this is an issue, right? Or am I misunderstanding the concept of languages and locales?

**Comment by alexander-schranz** [comment]
You are right this was an issue but is fixed with sulu/sulu#2676 (1.3.0-RC2) as mentioned here (sulu/sulu#2688).

**Comment by alexander-schranz** [comment]
maybe we should create a hotfix for 1.2.* version @danrot

**Comment by afroewis** [comment]
Thanks for the fast reply, I searched the issues in this repo but did not find https://github.com/sulu/sulu/issues/2688.

**Comment by danrot** [comment]
We decided not to backport this PR is too big, and the interface of the REST API changes, so it should not be done in a hotfix.
