### ISSUE TITLE
Categories are not rendered in default template

### ISSUE THREAD

**Issue by nnatter** [sulu/sulu-standard#740]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.0

#### Actual Behavior

Sulu does not render categories which are selected in the excerpt tab when using the default template.

#### Expected Behavior

Sulu should render the categories which are selected in the backend.

#### Steps to Reproduce

1. Select some categories in the excerpt tab of a page which uses the default template.
2. The categories are not visible when loading the page in the frontend.

#### Possible Solutions

This bug is caused by using `content.ext.excerpt.categories` instead of `extension.excerpt.categories` in the `default.html.twig` file.

**Comment by danrot** [comment]
That's actually the kind of stuff where creating a PR would be less work than creating an issue 😜
