### ISSUE TITLE
Assets not correctly generated in staging environment

### ISSUE THREAD

**Issue by DosCorazones** [sulu/sulu-standard#741]
I have a staging environment and all is running fine, except for the website assets.

With the basic setting assetic.use_controller: false in /app/config/website/config_stage.yml the assets are not correcly generated and delivered.

domain.tld/css/<hash>.css results in 404
domain.tld/js/<hash>.js results in 404

it seems that the assets are not bundled. To initialize the staging environment i use the following commands:
```
app/console sulu:build dev --env=stage --destroy --no-interaction
app/console cache:clear --env=stage
app/console assets:install --symlink --relative --env=stage
``` 

how can i further debug this, am i missing an important step, or is this simply a bug?!

**Comment by alexander-schranz** [comment]
only assetic will generate css or js under web/js and web/css so you need to run `app/console assetic:dump` when you use assetic for your assets.

**Comment by DosCorazones** [comment]
But shouldn't sulu:build generate the assets too?

Even if execute app/console assetic:dump afterwards, the assets cannot be served. Any further ideas? assetic:dump just outputs the information "dumping all <env> assets" and thats it. There is no sign of any generated files. Also tried -vvv but couldn't get more information out of that...

**Comment by alexander-schranz** [comment]
you can read more about assetic here: http://symfony.com/doc/current/assetic/asset_management.html. what is wrong with your assets is not a sulu issue because sulu do nothing with assets and let you include your css and js the way you like.

I would recommend you to include the assets without assetic e.g.: 

```twig
<link rel="stylesheet" href="{{ asset('/bundles/clientwebsite/yourtheme/css/style.css') }}">
```

when you really want to use assetic you need to check why your .css or .js files have no name. after assetic:dump assetic should generate the files into `web/css` and `web/js`.

**Comment by DosCorazones** [comment]
Okay, i'll take a look... 

But the weird thing is, when i create a sulu standard project, there is a default template. I duplicated that default template and just changed the pages templates afterwards. 

So, correct me if i'm wrong, as the default template from a plain sulu project also generates some css and js, isn't there some configuration that generates the css files for the default template? I'm talking about the bootstrap files in the standard ClientWebsiteBundle from a clean sulu-standard installation.

**Comment by alexander-schranz** [comment]
@DosCorazones yeah the default theme use assetic and if you run assetic:dump it will be done by the assetic bundle: http://symfony.com/doc/current/assetic/asset_management.html. maybe your user have no permissions to write to `web/css`. Thats why I recommend you not to use assetic just include them as I post it before.

Did you check if there are any files in web/css after you run `app/webconsole assetic:dump`?

**Comment by DosCorazones** [comment]
I did check that. There were no files. Access rights are correct. 
The funny part is, i didn't know app/webconsole until now... executing app/webconsole assetic:dump generated the files and everything is fine 👍 

Thanks for helping! I'm gonna re-read the parts in the sulu documentation about webconsole then.

**Comment by alexander-schranz** [comment]
@DosCorazones Sulu have 2 Kernels:

AdminKernel for admin `app/console` in the new sulu-minimal called `bin/adminconsole` 
and WebsiteKernel for Admin `app/webconsole` in the new sulu minimal `bin/websiteconsole`.

They can have both different configuration `app/config/admin` or `app/config/website`.  If you are doing things on the website you should use the websiteconsole if you are doing things on the admin you should use the adminconsole.

When you look at the both configuration only the website has assetic bundles registered:

1. https://github.com/sulu/sulu-standard/blob/1.3.0/app/config/website/config.yml#L8
2. https://github.com/sulu/sulu-standard/blob/1.3.0/app/config/admin/config.yml#L9

so only the website kernel know about them.
