### ISSUE TITLE
How to get blocks with content repositories methods?

### ISSUE THREAD

**Issue by nicodmf** [sulu/sulu-standard#747]
I think this is not à bug or a feature but more an explination : 

When i use the content repository with the field mapper, i don't have the blocks fields in the data array.

Can you guide me to have there data?

**Comment by alexander-schranz** [comment]
I'm not sure what you want to achieve but maybe this helps you:


```
        $object = ($this->get('sulu_document_manager.document_manager')->find(
            '3e211fdf-51ee-49c2-8e21-671a566211b4',
            'de'
        ));

        $test = $this->get('jms_serializer')->serialize(
            $object,
            'array',
            SerializationContext::create()
                ->setSerializeNull(true)
        );

        dump($test);

        exit;
```

**Comment by nicodmf** [comment]
I'm sorry i wrote on a phone and completion was ..;

Shortly, yes this work, but, i try to use the findByUuid method. because i want to have a complete list.

**Comment by nicodmf** [comment]
After test, with this code i have only the title

**Comment by wachterjohannes** [comment]
@nicodmf the content-repository is implemented to retrieve simple lists of nodes. it currently don't work for complex types like blocks. The problem there is that this values are not stored in a single property on the node. this makes it hard to write queries which matches this type of content. I think you have to use the document-manager to load this type of data.

Another good and fast way to achieve this is to use the search-index where you can store all the data you need directly. Use the MassiveSerach - SearchManager and the `sulu.search.field` tag in the templates to define indexed / stored data (https://github.com/sulu/sulu-standard/blob/d684aaf126e7bc5da677307a4d53ba1e0706d777/app/Resources/pages/example.xml.dist#L115)

**Comment by nicodmf** [comment]
But i can get property with $object->getStructure()->getProperty('repeatition')->getValue()

**Comment by wachterjohannes** [comment]
What do you mean with `$object`?

**Comment by danrot** [comment]
When using the `ContentRepository` you'll only get an array as data, and there is no document hydration happening. So no, what you are planning to do there is not possible that way...

**Comment by nicodmf** [comment]
I think i searched an simple hydration method after querying the node, and possibly without make another db request.

Thanks for your help.

I think this issue can be cloased, at least for me.

**Comment by danrot** [comment]
@nicodmf Feel free to close the next time on your own, or aren't you able to do that?
