### ISSUE TITLE
Sulu documentations

### ISSUE THREAD

**Issue by rflorent** [sulu/sulu-standard#748]
| Q | A
| Q | ---
| Bug? | no
| New Feature? | no
| Sulu Version | Sulu Standard 1.3
| Browser Version | Browser name and version

Hello, I'm little bit confused about the docs availables

I use the standard edition, docs linked on github page lead to 404
http://docs.sulu.io/en/latest/book/getting-started/index.html

http://docs.sulu.io/en/latest/book/getting-started.html
this docs is about minimal edition

http://docs.sulu.io/en/stable/book/getting-started/installation.html
This is about standard edition, and i follow this (don't know how i came on this docs)

There are differences between theses docs, like start a sever, adminconsole (i have no one file name like that...), folder var, in minimal edition

What are the best pratices ? Starting with minimal edition and adding bundles ?
I'm lost.

Thanks for all

**Comment by alexander-schranz** [comment]
@webmozart

**Comment by danrot** [comment]
You should start with the minimal edition and follow the documentation at http://docs.sulu.io/en/latest/book/getting-started.html

We have to see how we handle the situation with sulu-standard here...
