### ISSUE TITLE
Admin Theme Modification

### ISSUE THREAD

**Issue by jayesbe** [sulu/sulu-standard#749]
This is just a general question.. Is it possible to change the admin theme colour scheme?  

At the moment I have extended the AdminBundle with a "child bundle" and have copied over the resources.  I have been able to change the login theme for example a bit. However I wanted to also change the button colours and it looks like these are husky dependencies. 

Thanks for the advice and info.. and last, great job guys, I look forward to this becoming THE Symfony based CMS. Cause seriously.. who really likes Drupal lol. 
:+1:

**Comment by alexander-schranz** [comment]
Hello @jayesbe,

you could use the basic symfony way: http://symfony.com/doc/current/bundles/override.html.

Or you register your own bundle as admin bundle where you can add css and overrule the default css. And its correct the most css come from: https://github.com/massiveart/husky. 

Here the steps to register your own bundle and add css to it which can overrule the current css:

1. Create the Admin e.g. `src/Client/Bundle/WebsiteBundle/Admin/WebsiteAdmin.php`

```php
<?php

namespace Client\Bundle\WebsiteBundle\Admin;

use Sulu\Bundle\AdminBundle\Admin\Admin;

/**
 * Sulu WebsiteAdmin.
 */
class WebsiteAdmin extends Admin
{
    /**
     * {@inheritdoc}
     */
    public function getJsBundleName()
    {
        return 'clientwebsite/admin';
    }
}
```

2. Register the admin in your services.xml: `src/Client/Bundle/WebsiteBundle/Resources/services.xml`

```xml
        <service id="client_website.admin"
                 class="Client\Bundle\WebsiteBundle\Admin\WebsiteAdmin">
            <tag name="sulu.admin" />
            <tag name="sulu.context" context="admin" />
        </service>
```

3. Create the main.js `src/Client/Bundle/WebsiteBundle/Resources/public/admin/js/main.js`

```js
require.config({
    paths: {
        clientwebsite: '../../clientwebsite/admin/js',
        clientwebsitecss: '../../examplenews/admin/css'
    }
});

define(['css!clientwebsitecss/main'], function() {

    'use strict';

    return {

        name: "Client Website Bundle",

        initialize: function(app) {
        }
    };
});
```

4. Create the main.css `src/Client/Bundle/WebsiteBundle/Resources/public/admin/css/main.css`

```css
.sulu-login .content-container {
    background-color: red !important;
}
```

5. Build for production

For production you need build the js the builded files need to be inside: `src/Client/Bundle/WebsiteBundle/Resources/public/admin/dist/main.js`

**Comment by jayesbe** [comment]
@alexander-schranz  thank you for the very detailed example. Will give this a try tomorrow. 
:+1:

**Comment by marcelsanting** [comment]
Thx for this, it helped me customizing my Admin enviroment however the .sulu-login .content-container does nothing not even change to red. I am almost suspecting that main.css does not correspond with the login

**Comment by danrot** [comment]
@marcelsanting There is a separate file for the login, which includes the css on its own: https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/AdminBundle/Resources/views/Security/login.html.twig#L16

Are you aware of that? Might that be connected to your problem?

**Comment by rflorent** [comment]
`{"code":0,"message":"Catchable Fatal Error: Argument 1 passed to Sulu\\Bundle\\AdminBundle\\Navigation\\Navigation::merge() must be an instance of Sulu\\Bundle\\AdminBundle\\Navigation\\Navigation, null given"}`

This is what I get when I override admin css with a clientwebsite bundle, in admin interface.
It seem's that my WebsiteAdmin class must provide a navigation.
I disable it by editing admin pool merge navigation and testing null value before merge

**Comment by danrot** [comment]
The initial problem has been solved, so I am closing this issue.

**Comment by danrot** [comment]
The initial problem has been solved, so I am closing this issue.
