### ISSUE TITLE
Media Collections Lists doesn't load all items when browser window to big and no scrollbars appear

### ISSUE THREAD

**Issue by thgie** [sulu/sulu-standard#752]
| Bug? | yes
| Sulu Version | 1.3.0
| Browser Version | All
#### Actual Behavior

We have 22 Media Collections. On Display it loads a list with 20 items, and the rest when scrolled down. But if the Window is large enough to hold actually more then the 20 and the user can't scroll down, the rest won't be loaded.

**Comment by wachterjohannes** [comment]
hmm i think we listen on the scroll event to load the rest of the collections. TBH i don't see a good solution now how to solve this. we could load the next page until the available place is filled but a better solution would be to keep "breakpoints" which keep page-limits foreach window size. /cc @danrot

**Comment by thgie** [comment]
I know, it's not a problem with a clean solution. I generally would want the screen estate to decide what to do :)

I'd up the default loaded items to 25 or 30 and then add a visual feedback on how many items are left plus a possibility to load them manualy. In case the onscroll doesn't trigger, you at least see that there should be more items and that you can load them now if you'd like.

**Comment by wachterjohannes** [comment]
that seems also be a good solution @danrot can you add you thoughts?

**Comment by danrot** [comment]
Yeah, sounds like a good solution, but that's probably of no matter anymore with 1.4, because this component works different then. But on big screens we could get the same problem with the medias 😕

**Comment by danrot** [comment]
And @wachterjohannes please don't move the new issues to backlog, otherwise we loose focus of them.

**Comment by danrot** [comment]
@thgie Closing this one in favor of https://github.com/sulu/sulu/issues/2937, since the other one is in the correct repository.
