### ISSUE TITLE
Navigation Mapper does not return the navigation tree if locale code is country-specific (en-au)

### ISSUE THREAD

**Issue by eugenecorrea** [sulu/sulu-standard#754]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
| Browser Version | All browsers |
#### Actual Behavior

Twig navigation functions (eg. sulu_navigation_root_tree) cannot find any navigation items and returns an empty array if the site's locale is country-specific eg. "en-au", "en-us" etc. It works fine with other locale codes such as "en", "de", etc.
#### Expected Behavior

Navigation Mapper should return the navigation tree for locale codes such as "en-au", "en-us", etc.
#### Steps to Reproduce

1. Set 'en-au' as the default locale in config.yml
2. Add 'en-au' locale to sulu.yml
3. Set up webspace using 'en-au' as the default localization. Clear cache, build Sulu, etc.
4. Add a new page in the admin and add page to the navigation
5. Content is saved with the en-au locale but the Navigation Mapper still cannot find the pages for some reason.

**Comment by danrot** [comment]
I have just tried that out, but cannot reproduce it. Are you aware that you have to assign the pages a navigation in every language? Which exact configuration key are you talking about?

**Comment by eugenecorrea** [comment]
Sorry I forgot to note about the webspace setup. This is how I set it up to reproduce the issue.

`<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.1.xsd">

    <name>sulu.lo</name>
    <key>sulu_lo</key>

    <localizations>
        <localization language="en-au" default="true"/>
    </localizations>

    <theme>default</theme>

    <default-templates>
        <default-template type="page">default</default-template>
        <default-template type="homepage">overview</default-template>
    </default-templates>

    <templates>
        <template type="search">ClientWebsiteBundle:views:search.html.twig</template>
        <template type="error">ClientWebsiteBundle:views:error.html.twig</template>
        <template type="error-404">ClientWebsiteBundle:views:error404.html.twig</template>
    </templates>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="en">Main navigation</title>
                    <title lang="en-au">Main navigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>sulu.lo</name>
            <key>sulu_lo</key>

            <localizations>
                <localization language="en-au" default="true"/>
            </localizations>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="en-au">{host}/{localization}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url language="en-au">{host}/{localization}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="en-au">sulu131</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>`

**Comment by danrot** [comment]
@eugenecorrea Now I have spotted the error. You can't name the localization `en-au`, there is a language and a country property, as you can see in the documentation, e.g. [here](http://docs.sulu.io/en/latest/book/localization.html?highlight=country).

So your example should look like this (untested):

```
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.1.xsd">

    <name>sulu.lo</name>
    <key>sulu_lo</key>

    <localizations>
        <localization language="en" country="au" default="true"/>
    </localizations>

    <theme>default</theme>

    <default-templates>
        <default-template type="page">default</default-template>
        <default-template type="homepage">overview</default-template>
    </default-templates>

    <templates>
        <template type="search">ClientWebsiteBundle:views:search.html.twig</template>
        <template type="error">ClientWebsiteBundle:views:error.html.twig</template>
        <template type="error-404">ClientWebsiteBundle:views:error404.html.twig</template>
    </templates>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="en">Main navigation</title>
                    <title lang="en-au">Main navigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>sulu.lo</name>
            <key>sulu_lo</key>

            <localizations>
                <localization language="en" country="au" default="true"/>
            </localizations>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="en" country="au">{host}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url language="en" country="au">{host}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="en" country="au">sulu.lo</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>
```

You also shouldn't use the localization placeholder and a fixed language via XML attributes in the `URL` tag.

Does this solve your issue?

**Comment by eugenecorrea** [comment]
Ahh thanks that solves the issue :)
