### ISSUE TITLE
No preview available for copied pages

### ISSUE THREAD

**Issue by Elwe-Thingol** [sulu/sulu-standard#755]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Sulu Version | 1.3.0 |
| Browser Version | All browsers |
#### Actual Behavior

There is no preview available for copied pages, if they are not published. Error Message:
No Preview available
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 1 passed to Sulu\Bundle\DocumentManagerBundle\Bridge\DocumentInspector::getStructureMetadata() must implement interface Sulu\Component\Content\Document\Behavior\StructureBehavior, instance of Sulu\Component\DocumentManager\Document\UnknownDocument given, called in /home/customer/public_html/customer-location/vendor/sulu/sulu/src/Sulu/Component/Content/Mapper/ContentMapper.php on line 889 and defined") in "ClientWebsiteBundle:templates:default.html.twig" at line 11.

The preview is available as soon as the page is published.
#### Steps to Reproduce
1. Copy a page
2. Edit the copied page
3. Publish the page
4. Edit again the copied page

**Comment by danrot** [comment]
That should actually be fixed with https://github.com/sulu/sulu/pull/3014.
