### ISSUE TITLE
Permission "view" not granted on a new Webspace

### ISSUE THREAD

**Issue by aureliusm** [sulu/sulu-standard#759]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.1
| Browser Version | Chrome Version 54.0.2840.71 m

#### Actual Behavior

I created a new webspace with only sl locale - I don't need any other locales. I initialized sulu document by sulu:document:initialize and I gave the only admin/admin user all possible permissions in admin interface. When I click CONTENT inside my webspace in admin I get "403 Forbidden" one one of the calls and screen remains blank.

**The message is**: "Permission "view" in localization "sl" for object with id "" and of type "Sulu\Component\Content\Document\Behavior\SecurityBehavior" not granted"

**The call is**: http://sulu.dev/admin/api/nodes?webspace=webspace_name&language=sl&fields=title,order,published&exclude-ghosts=false&exclude-shadows=false&

#### Expected Behavior

I expect to see the tree structure to be able to add pages according to permissions that I set.

**Comment by aureliusm** [comment]
I forgot to set permissions to user. :-)

**Comment by danrot** [comment]
That's the kind of issues I like 🙈
