### ISSUE TITLE
Search Function - some translations are missing

### ISSUE THREAD

**Issue by Elwe-Thingol** [sulu/sulu-standard#763]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.3.0

#### Actual Behavior

Some Translations are missing in the search function. When I open the drop down menu there is no translation for the following translation keys:
search-overlay.index.page_sulu_io.title
search-overlay.index.page_spitex_intranet.title

#### Expected Behavior

There should be a translation for the mentioned translation keys.

#### Steps to Reproduce

1) Click on the search icon
2) Open the drop down menu next to the search bar

**Comment by danrot** [comment]
Just tested it, and it is working for me:
![image](https://cloud.githubusercontent.com/assets/405874/20564110/e895a106-b18b-11e6-9a62-31ee89b37aeb.png)

Can you try to purging the index with the `massive:search:purge` and reindex with the `massive:search:reindex` command? I think the keys you are talking about could be leftovers from old webspaces.

Could you also check if the request `/admin/search/indexes` returns the correct data? For the webspaces there should be an entry like this:

```
[{
    "indexName":"page_sulu_io",
    "name":"sulu.io",
    "securityContext":"sulu.webspaces.sulu_io",
    "contexts":[]
}]
```

**Comment by danrot** [comment]
Since there isn't more information coming I am closing this issue.
