### ISSUE TITLE
Settings - User roles - missing translations for the permission icons

### ISSUE THREAD

**Issue by Elwe-Thingol** [sulu/sulu-standard#764]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.3.0

#### Actual Behavior

When I hover over the permission icons I see the corresponding translation key.  The actual translation is missing.

#### Expected Behavior

There should be a translation for the translation keys.

#### Steps to Reproduce

1) Settings
2) User roles
3) Details
4) Hover over permission icons

**Comment by danrot** [comment]
Already fixed in https://github.com/sulu/sulu/pull/2774, should be fine with 1.4.0.
