### ISSUE TITLE
Page View - tab Permissions is not translated into german

### ISSUE THREAD

**Issue by Elwe-Thingol** [sulu/sulu-standard#765]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.3.0

#### Actual Behavior

The Tab Permissions is not translated into German.

#### Expected Behavior

The Tab Permissions should be translated into "Berechtigungen".

#### Steps to Reproduce

1) Open the page view
2) View the tab "Permissions"

**Comment by danrot** [comment]
Are you talking about the tabs? Seems to be translated for me:
![image](https://cloud.githubusercontent.com/assets/405874/20563547/5b370752-b189-11e6-8a2b-f6dcbba7a42d.png)

**Comment by Elwe-Thingol** [comment]
Permissions is translated now. Maybe the translation was missing in Version 1.3.0. (We now have Version 1.4.2) Thank you for the reply.
