### ISSUE TITLE
Text editor - multiple columns feature - the text in the columns is not at the same height

### ISSUE THREAD

**Issue by Elwe-Thingol** [sulu/sulu-standard#766]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.3.0

#### Actual Behavior

The text in the columns are not on the same height.

#### Expected Behavior

The text in the columns should be on the same height.

#### Steps to Reproduce

1) Open a text block
2) Add some text
3) Choose 2 or 3 columns

![capture_ink_li](https://cloud.githubusercontent.com/assets/17599335/20556724/a3cf47ca-b168-11e6-8302-8cad5f931893.jpg)

**Comment by danrot** [comment]
The part you have highlighted is in the preview, and therefore under you control. I can't see how this is a Sulu bug. Or is that only happening on the preview and not on the website?

**Comment by Elwe-Thingol** [comment]
The issue no longer exists. Thank you for your comment.
