### ISSUE TITLE
se_permissions "context" size column became to small

### ISSUE THREAD

**Issue by placid2000** [sulu/sulu-standard#768]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | any

#### Actual Behavior

Sulu:build command fails because the string persisted to context column in se_permissions is too long.
Field size is set to 60 chars. We need more since the persisted value is a string concatenation including the webspaceKey and there seems not be an easy and secure way to update the webspace key.

Our value : sulu.webspace_settings.{webspaceKey}.default-snippets exceeds the allowed 60 chars.

#### Possible Solutions
For example, increasing the field size to 64 or 128 chars.

**Comment by danrot** [comment]
@placid2000 Did you get an error message for that? Or was it failing silently?

**Comment by placid2000** [comment]
Executing sulu:buid dev throws the following error:

>  [Doctrine\DBAL\Exception\DriverException]
An exception occurred while executing 'INSERT INTO se_permissions (context, module, permissions, idRoles) VALUES (?, ?, ?, ?)' with params ["sulu.webspace_settings.sg_app_physioswiss_ch.default-snippets", null, 127, 1]:  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'context' at row 1

**Comment by danrot** [comment]
Ok, just thought about throwing an exception on our own, but I think this one is clear enough. So I'll just increase the size of the field.

**Comment by placid2000** [comment]
Great.
Is it going to be in the next release? Do we know the next release date? 
I'd like to avoid using dev-master.

**Comment by danrot** [comment]
@placid2000 I try to do a hotfix release next week.

**Comment by wachterjohannes** [comment]
#3091 is merged.
