### ISSUE TITLE
Deleting a former ghost page deletes the page in the other locale

### ISSUE THREAD

**Issue by afroewis** [sulu/sulu-standard#775]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2 (tried with sulu-minimal)

#### Actual Behavior

Two users:
"EnglishGuy" only has read & write permission in `en` locale
"Admin" can do anything in `de` + `en`

1. EnglishGuy creates a page in `en` locale
2. Admin creates a copy of the ghost page of the `en` locale in the `de` locale. 
3. Admin deletes the page in the `de` locale

This does not only delete the page in `de`, but also in `en`. 

#### Expected Behavior

Only the page in the current locale (`de`) should be deleted.

**Comment by danrot** [comment]
Deleting should actually work this way, and removing only the content of one locale is a missing feature we haven't implemented yet. The only problem I see here, is that the user should actually not be allowed to delete the page, if he doesn't have the permission to do so in all languages.

**Comment by afroewis** [comment]
@danrot Oh, ok, thank you. Should I add the `feature` tag to this issue or are you already tracking this? 

BTW: I think you misread something, I deleted the page with the Admin user (he has all permissions everywhere).

**Comment by danrot** [comment]
Actually I thought we already had an issue like that... But I can't find it anymore. Maybe you can create a new issue, which explains this feature (doesn't have anything to do with the permission stuff you've described here).

**Comment by afroewis** [comment]
Ok! Created issue https://github.com/sulu/sulu-standard/issues/776.

**Comment by danrot** [comment]
Just to be sure, it would not have been possible to delete the page without having the permissions for all languages?

**Comment by afroewis** [comment]
Ok, I just checked it and have bad news. I could delete a page with User_DE even though he only has write permissions in the `de` locale (but read permissions in all locales)... 

Should I create a separate issue for that?

**Comment by danrot** [comment]
@afroewis Yes, that would be awesome.

**Comment by afroewis** [comment]
Created  https://github.com/sulu/sulu-standard/issues/777.
