### ISSUE TITLE
Attempted to call an undefined method named "getPublished" of class "Sulu\Component\DocumentManager\Document\UnknownDocument"

### ISSUE THREAD

**Issue by ollietb** [sulu/sulu-standard#780]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | Chrome latest

#### Actual Behavior

How does Sulu behave at the moment? 

I've added a new pt language in the webspace like this

```
    <localizations>
        <localization language="en" default="true">
            <localization language="en" country="us"/>
            <localization language="en" country="gb"/>
        </localization>
        <localization language="pt">
            <localization language="pt" country="br"/>
        </localization>
    </localizations>
```

I set my environment URL like this
```
<environment type="dev">
    <urls>
        <url>cms.localhost/{language}</url>
    </urls>
</environment>
```
And added permissions for these languages for my contact and then finally in my `sulu.yml`

```
sulu_core:
    locales:
        de: Deutsch
        en: English
        fr: Français
        pt: Portuguese
    fallback_locale: 'en'
    translations: ['de', 'en', 'fr', 'pt']
```

When I use the language selector in the top right of the edit page to copy a source language

![select-language](https://cloud.githubusercontent.com/assets/342090/21426886/56a66d78-c849-11e6-8952-1965e7c071e1.png)

An ajax request is fired to `http://cms.localhost/admin/api/nodes/1155029f-8784-4e58-af16-cbbcfa7f4984?action=copy-locale&dest=pt&language=en&webspace=eventstag` and it has the error `Attempted to call an undefined method named "getPublished" of class "Sulu\Component\DocumentManager\Document\UnknownDocument"`

#### Expected Behavior

What is the behavior you expect?

All the content from the source node (text, images, blocks etc)  to be copied to the new language node

Also, I haven't looked too deeply into the issue yet but the preview area now shows an error "Preview not available Please change webspace."

**Comment by ollietb** [comment]
Also, when I use `sulu:content:locale-copy` on the command line I get this error
```
/mnt/c/xampp2/htdocs/cms# app/console sulu:content:locale-copy eventstag en pt --dry-run
PHP Fatal error:  Call to undefined method Sulu\Component\DocumentManager\Document\UnknownDocument::getPublished() in /mnt/c/xampp2/htdocs/cms/vendor/sulu/sulu/src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategy.php on line 142
```

**Comment by ollietb** [comment]
If I try to do the same thing on another page I get a different error

http://cms.localhost/admin/api/nodes/4a807b97-559a-4ffa-a9de-d6c8c37b32a0?action=copy-locale&dest=pt_br&language=en&webspace=eventstag

```
500 Internal Server Error - ResourceLocatorNotFoundException

Stack Trace

in vendor\sulu\sulu\src\Sulu\Component\Content\Types\ResourceLocator\Mapper\PhpcrMapper.php at line 134   -
            return $result;
        }
        throw new ResourceLocatorNotFoundException();
    }
    /**
at PhpcrMapper ->loadByContent (object(Node), 'eventstag', 'pt_br', null) 
in vendor\sulu\sulu\src\Sulu\Component\Content\Types\ResourceLocator\Mapper\PhpcrMapper.php at line 194   +
at PhpcrMapper ->loadByContentUuid ('1155029f-8784-4e58-af16-cbbcfa7f4984', 'eventstag', 'pt_br', null) 
in vendor\sulu\sulu\src\Sulu\Component\Content\Types\ResourceLocator\Strategy\ResourceLocatorStrategy.php at line 210   +
at ResourceLocatorStrategy ->loadByContentUuid ('1155029f-8784-4e58-af16-cbbcfa7f4984', 'eventstag', 'pt_br') 
in vendor\sulu\sulu\src\Sulu\Component\Content\Types\ResourceLocator\Strategy\ResourceLocatorStrategy.php at line 115   +
at ResourceLocatorStrategy ->generate ('Social Wall', '1155029f-8784-4e58-af16-cbbcfa7f4984', 'eventstag', 'pt_br') 
in vendor\sulu\sulu\src\Sulu\Component\Content\Mapper\ContentMapper.php at line 495   +
at ContentMapper ->copyLanguage ('4a807b97-559a-4ffa-a9de-d6c8c37b32a0', '1', 'eventstag', 'en', array('pt_br')) 
in vendor\sulu\sulu\src\Sulu\Bundle\ContentBundle\Repository\NodeRepository.php at line 783   +
at NodeRepository ->copyLocale ('4a807b97-559a-4ffa-a9de-d6c8c37b32a0', '1', 'eventstag', 'en', array('pt_br')) 
in vendor\sulu\sulu\src\Sulu\Bundle\ContentBundle\Controller\NodeController.php at line 766   +
```

**Comment by alexander-schranz** [comment]
@ollie 

1. the sulu_core locales are only for the translations in the backend if you dont translate the backend into `pt` you should not add it as locales under `sulu_core`: 

the only thing you need todo when add a new language add it to your `webspace.xml` and run `app/console sulu:document:initilaize` this create the required root documents for your language!

**Comment by alexander-schranz** [comment]
@danrot, @wachterjohannes it seems that the parentUuid is false at https://github.com/sulu/sulu/blob/69a6743155047ef31de432407a63c7906a4d7a56/src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategy.php#L105 it is the `/cmf/<webspaceKey>` node think this should be null.

**Comment by danrot** [comment]
@ollietb Did running the `sulu:document:initialize` command as @alexander-schranz described help? Should be the solution, then we could close this issue.

**Comment by danrot** [comment]
@ollietb The copy locale for the homepage should be working again, and I assume that the other error is fixed with @alexander-schranz comment. Please reopen if I am wrong.
