### ISSUE TITLE
Cropping is different in Content and Media sections

### ISSUE THREAD

**Issue by ollietb** [sulu/sulu-standard#781]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | Chrome latest

#### Actual Behavior

The crop function does not work very well from the edit page. I get the error "The orginal image is too small". I'm also more restricted in the crops I can do.

#### Expected Behavior

To be able to crop in the same way as in the Media section

#### Steps to Reproduce

From the edit page:
![crop-edit](https://cloud.githubusercontent.com/assets/342090/21429555/3e5b5da6-c857-11e6-9e6a-4795b5e8ade5.png)

Same image from the Media page:
![crop-media](https://cloud.githubusercontent.com/assets/342090/21429567/4cc4ade8-c857-11e6-83c0-87d92a8af648.png)

**Comment by danrot** [comment]
Fixed in sulu/sulu#3139
