### ISSUE TITLE
Crop preview area doesn't represent the real crop

### ISSUE THREAD

**Issue by ollietb** [sulu/sulu-standard#782]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | Latest Chrome

The crop we are using for one of our images is 

```
    <format>
        <name>1440x-scale</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">1440</parameter>
                </parameters>
            </command>
        </commands>
    </format>
```

We'd like to check the crop in the Media section.

#### Actual Behavior

The crop doesn't represent the actual file that is cropped. It is cropping the image rather than resizing it to fit within the bounds. I'm worried that if I save it then it will not resize the image but crop it instead.

#### Expected Behavior

The crop function shouldn't crop the image, the image should be resized within the bounds. It would be nice if I could then zoom in to crop if I choose, but it shouldn't enforce outbound image cropping when that option isn't set.

#### Steps to Reproduce

![sulu-media-crop-1440](https://cloud.githubusercontent.com/assets/342090/21430406/fe16c6b4-c85a-11e6-9fcd-eae144e195f5.png)

This is the actual image that is resized using the `1440x-scale` image format in the xml file (it is resized, not cropped)

![434-homepage-hero-foreground-web2](https://cloud.githubusercontent.com/assets/342090/21430491/510d08f6-c85b-11e6-83d0-45d9be5df4b4.png)

#### Possible Solutions

* Don't allow cropping if the image-format doesn't allow it.
* Allow cropping but don't enforce the cover size restraint

**Comment by danrot** [comment]
fixes in #3138
