### ISSUE TITLE
JavaScript editor with Adobe SDK on live environment

### ISSUE THREAD

**Issue by ollietb** [sulu/sulu-standard#784]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.2
| Browser Version | Chrome latest

#### Actual Behavior

When clicking the "Edit original image" in the Edit dropdown from the Media section the modal opens with the information about saving the image on an external website but then the Adobe edit UI doesn't open.

I'm getting this error in the console
```
husky.min.js?v=1479990153747:1 GET https://feather.aviary.com/imaging/v3/editor.js?v=1479990153747 net::ERR_INSECURE_RESPONSE
req.load @ husky.min.js?v=1479990153747:1
load @ husky.min.js?v=1479990153747:1
load @ husky.min.js?v=1479990153747:1
fetch @ husky.min.js?v=1479990153747:1
check @ husky.min.js?v=1479990153747:1
enable @ husky.min.js?v=1479990153747:1
enable @ husky.min.js?v=1479990153747:1
(anonymous) @ husky.min.js?v=1479990153747:1
(anonymous) @ husky.min.js?v=1479990153747:1
each @ husky.min.js?v=1479990153747:1
enable @ husky.min.js?v=1479990153747:1
init @ husky.min.js?v=1479990153747:1
(anonymous) @ husky.min.js?v=1479990153747:1

husky.min.js?v=1479990153747:1 Uncaught Error: Script error for: //feather.aviary.com/imaging/v3/editor.js
http://requirejs.org/docs/errors.html#scripterror
    at makeError (husky.min.js?v=1479990153747:1)
    at HTMLScriptElement.onScriptError (husky.min.js?v=1479990153747:1)
```

#### Expected Behavior

The Adobe integration works well on our dev environment with the same key

**Comment by ollietb** [comment]
I don't know if it has something to do with this information from the Adobe website

```
Editor Javascript Url
http://feather.aviary.com/imaging/v3/editor.js ("feather.js")

SSL-secure page? Please use this location (via Amazon Cloudfront):
https://dme0ih8comzn4.cloudfront.net/imaging/v3/editor.js

Note: Please always call this script directly, as there are some server-side dependencies.
```

Our website it hosted on a secure website

**Comment by wachterjohannes** [comment]
@marcelmoosbrugger what do you think? this could be a problem. but currently we are not in the office maybe someone has time after christmas to check that.

**Comment by danrot** [comment]
@ollietb I think that's what has been fixed with https://github.com/sulu/sulu/pull/3140, right? Please reopen if you think otherwise.
