### ISSUE TITLE
Blocks position don't work anymore in 1.4.3

### ISSUE THREAD

**Issue by rflorent** [sulu/sulu-standard#785]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| 1.4.3

#### Actual Behavior
Blocks are not movable anymore, the button "move" disapear
There is an error message from aura in the js console :
"UserSettings are not loaded"

#### Expected Behavior

Blocks should be movable

#### Steps to Reproduce

Install a sulu minimal version

#### Possible Solutions

Downgrade to 1.4.2 resolve the problem

**Comment by alexander-schranz** [comment]
@danrot maybe todo with the changes in https://github.com/sulu/sulu/pull/3108

**Comment by danrot** [comment]
Fixed in sulu/sulu#3130
