### ISSUE TITLE
type in media selection does not work

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#786]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.8 and 1.4.2 tested - same problem
| Browser Version | all

#### Actual Behavior

If you create the page-property `media_selection` and set the parameter `type` with value `image` then you can select on admin-site images and videos (not tested with documents).

#### Expected Behavior

The media selection should only show the media types which are defined in the `types` parameters. And only this media types should be selectable.

#### Steps to Reproduce

See `Actual Behavior` above.

```xml
<property name="images" type="media_selection">
    <meta>
        <title lang="en">Images</title>
    </meta>

    <params>
        <param name="types" value="image"/>
    </params>
</property>
```

**Comment by danrot** [comment]
Fixed in #3162
