### ISSUE TITLE
Error while running sulu:document:initialize on a fresh installation

### ISSUE THREAD

**Issue by mtnorthrop** [sulu/sulu-standard#789]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.3
| Browser Version | None (issue is with console)

I'm trying to install Sulu by following the installation instructions here: http://docs.sulu.io/en/latest/book/getting-started.html

While the `sulu:document:initialize` command is running as part of the `bin/adminconsole sulu:build dev` command, a Symfony FatalThrowableError is thrown with this message: `Parse error: syntax error, unexpected ')'`.

This appears right after `sulu_core.webspace.document_manager.webspace_initializer` is echoed to the console.

Repeated attempts at running just `sulu:document:initialize` throw the same error.

This is my very first attempt at installing Sulu, so I'm not sure where I should start to look to fix this issue.

My development environment is: Ubuntu 16.04, PHP 7 and using MySQL 5.7.

As per the installation instructions, I've installed sulu/sulu-minimal, but I'm posting this error report here as this seems to be Sulu's main issue board.

Thanks in advance for any hints on how to fix this!

**Comment by alexander-schranz** [comment]
Hello and welcome @mtnorthrop,
most of the code of sulu is in https://github.com/sulu/sulu so that is mostly the main issue board but its not a big problem posting your issues here. I think your installation failed because of twig 2.0. The hotfix for  it was done but not released you can switch to use `develop` or `master` of `sulu/sulu`.

If you want to stay on the stable release version you can add the following to your `composer.json` to use Twig 1 until the hotfix is released. 

```
"require": {
    ...
    "twig/twig": "^1.11"
}
```

**Comment by thomasduenser** [comment]
@mtnorthrop I've just had the same issue and the solution from @alexander-schranz seems to work!

**Comment by mtnorthrop** [comment]
Hello @alexander-schranz and @thomasduenser ,

Thanks very much for your (very quick) replies; I really appreciate it. 

I've set the version of `twig/twig` in my project's `composer.json` file to `^1.11` and now the `bin/adminconsole sulu:build dev` command completes without error.

Thanks also for pointing out the `sulu/sulu` repo's issue board; I'll post any further questions there if I'm not able to find the solutions on my own.

**Comment by alexander-schranz** [comment]
@mtnorthrop the new version 1.4.4 is released and supports now twig 2.0.

**Comment by mtnorthrop** [comment]
@alexander-schranz 

Thanks for the notice! So it looks like we can just install 1.4.4 now, and don't have to set the twig/twig version manually any more.
