### ISSUE TITLE
Publishing doesn't flush website cache

### ISSUE THREAD

**Issue by spras** [sulu/sulu-standard#791]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.4.5
| Browser Version | Chrome 55.0.2883.95

#### Actual Behavior

When I publish a modification on a page already online, the website cache is not flushed, i don't immediately see my modification online.

#### Expected Behavior

When I publish a modification on a page already online, the website cache is flushed, and i immedialty see my modification online.

#### Steps to Reproduce

On prod env : 
With HTTPS on admin and on websiite
With a real domain configured in the webspace portal environnement url , don't leave {host} 
Publish a modif on a page, display the page on the website

**Comment by danrot** [comment]
I've just tried that on the master branch and it is working for me, there only seems to be an error on develop... But maybe you are experiencing a different issue than I have... Can you check the log files of Sulu and check if there are any errors?

**Comment by spras** [comment]
I was on the 1.4.3 version, updated to the 1.4.5 , but it was steal the same behavior

Nothing in log files 

will PR for #3149 will fix it in the next release ?

**Comment by wachterjohannes** [comment]
Hmm i have seen that the implemented fix is for a bug which was introduced in develop. so- if you use 1.4.5 the fix does nothing change for you.

I think you use the symfony-http-cache and not varnish? Correct me if i am wrong.

You should see in the log following line (if logging is on for prod) `[CACHE] INVALIDATING [%s]: %s`. This indicates that a purging is scheduled. If then happens an error the cache was not cleared if you dont see something the cache should be cleared.

Another thing which could be that your browser caches the response of the url (which will also be done for a short amount of time). then the request wont be done at the server.

Could you please give me feedback for this?

**Comment by spras** [comment]
I use symfony-http-cache 

i think logging is on on prod because i have files : var/logs/website/prod/prod.log and var/logs/admin/prod/prod.log, but nothing show up in theses files when i publish my page, or when i flush website cache.

it's not browser cache, il see the access log on the server, and have the same old page  on other browsers.

in the response headers i have : 
Age:331
Cache-Control:max-age=240, public, s-maxage=240, max-age=0

Age grows up on each request, until i flush the website cache il the back-office.

thank's for your help

**Comment by alexander-schranz** [comment]
@spras just to be sure the client side cache is disabled in the chrome webdev tools? because as you see the page itself is cached for 240 seconds on the client browser. If you have a proxy in your company the proxy will also cache it for 240 seconds.

**Comment by spras** [comment]
no client side cache, no company proxy , the site is on HTTPS , but nothing else : https://cms.hmdiffusion.com/

**Comment by alexander-schranz** [comment]
@spras can you check if it does locally work on PROD environment? And can you maybe check if it works correctly without https?

**Comment by spras** [comment]
yes, i was trying to do that, and it works.

Now, i'll try to add https localy.

**Comment by spras** [comment]
here it is, with https i reproduce the bug localy, (env prod of course)

**Comment by alexander-schranz** [comment]
ok then it seems to be related to #2929
@sulu/core-team seems like we need to have a look again into that issue because it seems not to be fixed in 1.4.3

**Comment by spras** [comment]
FYI i updated to 1.4.5, and i have the same behavior.

I also notice that the PURGE request is send and respond code 200 => but on http  , not on https

my page on http is updated, but the same page on https is the old cached one.

Do we have to configure the scheme some where to tell sulu admin to purge on the right scheme ?

**Comment by spras** [comment]
More infos : 

When i configure my webspace with : ```<url language="fr">cms.hmdiffusion.com</url>```  It doesn't works

When i configure my webspace with : ```<url language="fr">https://cms.hmdiffusion.com</url>```  It doesn't works

When i configure my webspace with : ```<url language="fr">{host}</url>```  It works ! 

But i ran i an other issue ? ... I have 3 webspaces , if i set  ```<url language="fr">{host}</url>```  on the 3 webspaces, the 3 sites render the same webspace ... 

What's the good practice to configure the webspaces URLs ? 

Thank's for your help

**Comment by wachterjohannes** [comment]
@spras could you try the linked PR with your code. it seems that we have forgotten to generate urls with `https` at this place. The given fix should do it!

**Comment by spras** [comment]
@wachterjohannes 👍  it's ok with this patch 
hope it will be released soon 

Thank's you very much

**Comment by wachterjohannes** [comment]
there will be a HOTFIX with such a fix soon (:

**Comment by danrot** [comment]
@spras The code was changed once more, do you want to test it again?

**Comment by spras** [comment]
@danrot : it's ok for me, it's works

**Comment by danrot** [comment]
fixed in sulu/sulu#3150
