### ISSUE TITLE
Cannot add a hashtag to internal links

### ISSUE THREAD

**Issue by aureliusm** [sulu/sulu-standard#793]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
#### Actual Behavior

You cannot add a hashtag if you select internal link in page settings.

#### Expected Behavior

It would be great to be able to add an optional hashtag to internal links.

**Comment by danrot** [comment]
@berndhep What do you think about that? Should we add this? And if yes, should it simply be another field in the white box that appears when `internal link` is selected?

**Comment by berndhep** [comment]
@danrot Sounds legitimate but let's discuss possible side issues first.

**Comment by danrot** [comment]
@aureliusm We have discussed this feature request, but we decided against implementing it. The problem with these hashtags is, that we don't have any possibility to check whether they really exist or not. And that's actually the strength of the internal link page type: It is guaranteed that the destination exists. So a workaround for what you want to do is to use the external link content type, I hope that is ok for you.
