### ISSUE TITLE
Datagrid rename results of column

### ISSUE THREAD

**Issue by AndreFromentalAcelys** [sulu/sulu-standard#796]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | Sulu Minimal

Hi, I'm actually use my own entity with native datagrid feature of Sulu.

I've implemented this tutorial : http://blog.sulu.io/how-to-develop-a-bundle-in-the-sulu-admin-1
It's work, and print my datas.

I have a boolean property in my Doctrine entity wich is mapped in datagrid.
My problem is that I wanna rename the content of the column who match the boolean property.

In fact, if the result of the boolean property is false I wanna print "No" in column result of the datagrid.
If  the result is true, I wanna print "Yes".

How can I do that ?

Thanks for your help !

Best Regards,

André

**Comment by wachterjohannes** [comment]
there is a feature in the datagrid named `contentFilters` which enables you on javascript side to change data of a column. see https://github.com/sulu/sulu/blob/develop/src/Sulu/Bundle/AutomationBundle/Resources/public/js/components/automation-tab/main.js#L147

you can specify a function which gets the api-content and returns the content which should be displayed.

I will close this issue if this dont fixes for you please reopen (:

**Comment by AndreFromentalAcelys** [comment]
Hi thanks for you reply.

I tried it but doesn't work for me.
I've done it in my _list/main.js_ but it do nothing :/ .

**Comment by wachterjohannes** [comment]
do you want an own column or add it to a existing column?

**Comment by AndreFromentalAcelys** [comment]
I just want to change the text of a **result** column.

Actually I have a datagrid listing my entity.
One of the property is a boolean, so when I print all the datas of the entity I've got "true" or "false" in result.

I just want to change this to "Yes" or "No" in the datagrid line.

The apply of `contentFilters` didn't change nothing.

**Comment by wachterjohannes** [comment]
can you post your configuration of the datagrid?

**Comment by danrot** [comment]
ping @AndreFromentalAcelys
