### ISSUE TITLE
How to translate entitites ?

### ISSUE THREAD

**Issue by toxicity1985** [sulu/sulu-standard#801]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | Last Version
| Browser Version | Browser name and version

Hey,

I followed the tutorial to create an external bundle with entities. It works well but now, i want to translate it and i don't find a way to do it. I want to add and use the top "switcher language".
Can you explain the procedure to do this ?

Thanks.

**Comment by alexander-schranz** [comment]
@toxicity1985 to get the language switcher you need to add it to your header toolbar e.g.:

```
            header: function() {
                return {
                    title: 'app.my_items',
                    noBack: true,
                    underline: false,

                    toolbar: {
                        languageChanger: {
                            preSelected: this.options.language // come from your route definition
                        },
                        buttons: {
                            add: {},
                            deleteSelected: {}
                        }
                    }
                }
            },
```

your frontend routes need also be localized that the language switcher works and you get this.options.language correctly to use it in your apis.

**Comment by toxicity1985** [comment]
Thank you. And how can i get the current language to send it to the component ?
And what's the best way to translate entities, duplicate all the entity with the traduction or add doctrine translator ?

**Comment by alexander-schranz** [comment]
@toxicity1985 as said if you done the routing correctly your locale is under `this.options.language` available you need to add it to your api calls.

To translate an entity you create e.g.: a News Entity and a NewsTranslation entity (with a field locale). So the database look like this:

```
app_news
    id: integer e.g.: 1

app_news_translations:
    id: integer e.g.: 4
    idNews: integer e.g.: 1
    locale: string e.g.: en
    title: string e.g.: Test
    description: text e.g.: <p>Test</p>
```

when you call `/admin/api/news?locale=en` your api should return something like:

```json
{
    "id": 1,
    "locale": "de",
    "title": "Test",
    "description": "<p>Test</p>",
}
```

when you create the `de` you just need to create a NewsTranslation entity and add it to the exist News entity.

**Comment by toxicity1985** [comment]
Ok, it's what i think and for the route it's something like that. So, thank you for your informations.

> sandbox.mvc.routes.push({
>             route: 'contacts/contacts/edit::id/:content',
>             callback: function(id, content){
>                 this.html(
>                     '<div data-aura-component="contacts@acmecontact" data-aura-content="'+content+'" data-aura-id="' +id + '"/>'
>                 );
>             }
>         });

**Comment by toxicity1985** [comment]
Ok i have to make a locale listener and injecting it in my service !
