### ISSUE TITLE
Put comment in content

### ISSUE THREAD

**Issue by syeikhanugrah** [sulu/sulu-standard#805]
How to put a comment on the content?

**Comment by wachterjohannes** [comment]
@syeikhanugrah i am no 100% sure what did you want (: but we have a working prototype for user-generated-comments https://github.com/sulu/SuluCommentBundle give us some feedback if you will use it. if you have further questions subscribe to our slack channel http://sulu.io/en#question

**Comment by alexander-schranz** [comment]
@syeikhanugrah if you want to add in the backend to a field a comment for the content manager use the info_text: http://docs.sulu.io/en/latest/book/templates.html?highlight=info_text#help-text
