### ISSUE TITLE
No save after toggle toggler in block

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#809]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.2

#### Actual Behavior

If you have a toggler on the page and toggle it, then the save button is disable.
You need to change everything else to enable the save button.

#### Expected Behavior

When toggle the toggler, the save button should be enabled.

#### Steps to Reproduce

Add checkbox with type toggler to template.
Toggle the toggler and try to save.

**Comment by danrot** [comment]
That's also working for me...

**Comment by dmetzler1988** [comment]
This only occurs if you have block elements.

**Comment by dmetzler1988** [comment]
Seems to be obsolete - this works in Sulu 2.0
