### ISSUE TITLE
Contact Position

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#811]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.2

#### Actual Behavior

If you have a contact and add a company and you will now add a position, then you can't do it.
You need to save the contact with the new company and make a page reload. Now you can create or select a position.

#### Expected Behavior

The position should be selectable without saving and reloading the page after selecting a company.

#### Steps to Reproduce

Open an existing contact and add a company.  
Now try to select a position.

**Comment by danrot** [comment]
I tried to reproduce that issue, but I couldn't. If I add a company the dropdown gets activated. Can you double-check if it is a real issue? I've tested in chrome, which browser are you using?
