### ISSUE TITLE
Social media links to contact

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#812]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.5.2

Add social media links to contact.

Maybe a dropdown to select a social media and add the link to it. Make this with a option to add more social media links to this contact (like this with email address as example).

**Comment by danrot** [comment]
@dmetzler1988 There is already #508 for that. And please use our issue template, instead of simply deleting all the headings. Also, new issues should be created in the sulu/sulu repository, since they should be fixed there almost every time.

Closing it as duplicated.
