### ISSUE TITLE
Global content across all pages - snippets?

### ISSUE THREAD

**Issue by zymsys** [sulu/sulu-standard#815]
Let me know if there is a better place to ask for this kind of help.

I've got a request to have a top nav on the site which is really a global list of 'internal_links'. I've tried to do this with snippets by adding a top nav item to snippets/default.xml like so:

        <property name="topnav" type="internal_links">
            <meta>
                <title lang="en">Top Navigation Links</title>
            </meta>
        </property>

I don't want to add a snippet property to my page and have the user select this snippet on every instance of a page, so I copied the UUID out of the admin URL and used it in the template like so:

          {% set default_snippet = sulu_snippet_load('353aad8b-93e8-4980-8107-8afd0667a5e4') %}

I was hoping to be able to do something that didn't hard code the UUID, but this didn't work:

          {% set default_snippet = sulu_snippet_load_default('default') %}

Is there a better way?

**Comment by thomasduenser** [comment]
Hello!

The second call with `sulu_snippet_load_default` is the right one for you - it expects the `snippetType` as an argument. There are two things you need to do to make it work:

1. Change your configuration to enable the selection of default snippets:
```
sulu_snippet:
    types:
        snippet:
            default_enabled: true
```

2. Select the snippet you've created in the webspace settings.

More information can be found in our docs:
[Default Snippets](http://docs.sulu.io/en/latest/cookbook/default-snippets.html) and [sulu_snippet_load_default](http://docs.sulu.io/en/latest/reference/twig-extensions/functions/sulu_snippet_load_default.html)

I hope it is clear now!
Thomas

**Comment by zymsys** [comment]
Yes, that was all I needed. Much appreciated!

**Comment by alexander-schranz** [comment]
@zymsys if you just want to have a flat navigation and not a tree you can use the `sulu_navigation_root_flat`

**Comment by zymsys** [comment]
Thanks @alexander-schranz, that's good to know. In this case we want to 'cherry pick' certain items for the top nav so I think the internal_links property is a good fit.

**Comment by alexander-schranz** [comment]
@zymsys if it fits for your case its good, but want also to mention that you can also create a page which is a internal link to another page (Settings Tab) and add it to the navigation context. This is typically used when you want to add a page to the navigation item where this page is not in the current tree.
