### ISSUE TITLE
Nesting blocks

### ISSUE THREAD

**Issue by ilyasavitski** [sulu/sulu-standard#817]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.5.3
| Browser Version | Google Chrome 58.0.3029.96

Is there any plans to implement nesting blocks?

**Comment by alexander-schranz** [comment]
Hello @ilyasavitski,

have a look at https://github.com/sulu/sulu/issues/3199 and subscribe it if you want to stay up2date.
