### ISSUE TITLE
Discrepancy in urls between workspaces when moving pages within Sulu admin interface

### ISSUE THREAD

**Issue by dalailomo** [sulu/sulu-standard#818]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5
| Browser Version | Chrome 58

#### Actual Behavior

When moving pages within the Sulu admin interface, the urls generated in the sitemap still show the old url for those pages (unless going to the page and save it again, then updates the url to the correct one).

#### Expected Behavior

These urls should be changed as well without any other additional steps.

#### Steps to Reproduce

Within the Sulu admin interface:

- Create a couple of pages `Page A` and `Page B`
- Create some sub pages on each of those two pages
- Move `Page B` into `Page A`
- Generate a sitemap and you will see that the `Page B` and their subpages still have the old the url

#### Possible Solutions 

One solution that works is just to go to those pages and save them again one by one in the admin interface. That will update the url to the correct one. The problem with this solution is if the amount of pages is considerably high (like 400 pages)... then it becomes an extremely time consuming task.

#### Questions

Given that we have two workspaces `default` and `default_live`:

After some research (using a phpcr browser), we found that the moved nodes in the `default_live` workspace still got the value of the old url in the properties. The nodes in the `default` workspace otherwise are correctly updated so then we have this discrepancy between the two workspaces. 

Is there an alternative way to solve these problem 'automagically'?

Please let me know if you need more information.

Thanks! 😃

**Comment by danrot** [comment]
I think @wachterjohannes has put some work into sitemaps, since you've created that issue... Maybe he already fixed what you are describing?

**Comment by wachterjohannes** [comment]
@dalailomo the problem sounds known and I think that should be fixed in 1.6! are you able to check that?

**Comment by dalailomo** [comment]
@danrot @wachterjohannes thanks for the responses.

Sure, I will check it as soon as I can 👍 . Thanks!

**Comment by dalailomo** [comment]
@danrot @wachterjohannes I just checked and it works as expected 👍 .

Thanks for the help!

Closing this issue.
