### ISSUE TITLE
How to translate organizations

### ISSUE THREAD

**Issue by ilyasavitski** [sulu/sulu-standard#820]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.5.3
| Browser Version | Google Chrome Version 58.0.3029.110 (64-bit)

Is there any way to translate organizations? I'm using this information in front-end and would like to have possibility to get it in different languages.

**Comment by wachterjohannes** [comment]
Currently, there is no way to manage users/organizations in different languages. What usecase did you have? could also Snippets be an option for you?

**Comment by ilyasavitski** [comment]
I have 2 languages en (prim) and ru. You can check [this page](http://lamyra.org/en/contact-us) to get what i mean.

**Comment by wachterjohannes** [comment]
If you manage you contacts within the snippets (own template) you can translate them in the same languages than the pages. would that be a solution for you?

**Comment by ilyasavitski** [comment]
Yes, it could be the solution, not very comfortable, but nevermind... Thank you

**Comment by wachterjohannes** [comment]
@ilyasavitski I will close this issue. if you think it is not fixed for you feel free to reopen it!
