### ISSUE TITLE
Filed to remove directory exception on build process

### ISSUE THREAD

**Issue by dmartuszewski** [sulu/sulu-standard#822]
Hi, 
When I run
`bin/adminconsole sulu:build dev`
it ends up with the cache:clear exception

>  [Symfony\Component\Filesystem\Exception\IOException]                                             
          Failed to remove directory "/home/vagrant/Code/example.com/var/cache/admin/de~/sulu": .  

I'm running Sulu on Homestead.

**Comment by wachterjohannes** [comment]
have you run `bin/adminconsole sulu:build`? did you receive the same error?

**Comment by danrot** [comment]
There was a similar issue on stackoverflow, seems to be vagrant related. Can you see if the answer there fixes your problem? https://stackoverflow.com/questions/43829144/sulu-cms-installation-errors-with-laravel-homestead

**Comment by dmartuszewski** [comment]
It was vagrant connected @danrot!
Switching to NFS helped.
Homestead.yml:
`folders:
    - map: /media/dan/Projects
      to: /home/vagrant/Code
      type: "nfs"`
