### ISSUE TITLE
Migrate from sulu-minimal to sulu-standard

### ISSUE THREAD

**Issue by ilyasavitski** [sulu/sulu-standard#825]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.5.3

Is there any way to migrate from sulu-minimal to sulu-standard edition?

**Comment by wachterjohannes** [comment]
sulu-standard will be abandoned in the near future. See the issue https://github.com/sulu/sulu-standard/issues/792#issuecomment-273804627 from @alexander-schranz where he describes the differences.

Which usecase do you have and why do you want to migrate to sulu-standard?

**Comment by danrot** [comment]
I also don't see any reason to do a "downgrade" to sulu-standard. You can continue to discuss this in here, but I think the issue itself can be closed.
