### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by ilyasavitski** [sulu/sulu-standard#827]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

Please add fileinfo extension for PHP as requirement in the documentation.

**Comment by wachterjohannes** [comment]
this dependency is not a hard requirement (only if you use media-bundle and there for mime-type guessing). But we should add this extension to the documentation. Do you have any issues with that?

**Comment by ilyasavitski** [comment]
I had some issues after deploying to public hosting. Now everything is ok. Sorry, i didn't get where should i write such a proposition - so i wrote it here :)

**Comment by wachterjohannes** [comment]
no problem (: could you please create an issue in the https://github.com/sulu/sulu-docs repository? then we can close this issue here.

**Comment by ilyasavitski** [comment]
Done :)
