### ISSUE TITLE
Attempted to call function "oci_connect" from namespace

### ISSUE THREAD

**Issue by banach600** [sulu/sulu-standard#829]
Hi all,

I'm using Symfony 3.3.0, and I have an incomprehensible problem with the function oci_connect. Using the web browser I have all works fine. But when using the console I obtain the following error 
 
> [Symfony\Component\Debug\Exception\UndefinedFunctionException]               
  Attempted to call function "oci_connect" from namespace "ImportBundle\ImportFunctions". 

I add that oci_connect is used in a service ImportBundle\ImportFunctions\OraCon. Thanks to anyone who can help me with this problem.

**Comment by wachterjohannes** [comment]
@banach600 I think you run different versions of Sulu (and extensions) in your browser and CLI.

But tbh I don't think that this is related to Sulu if I am wrong, feel free to reopen this issue.
