### ISSUE TITLE
Hidden description field editor on Excerpt & Categories tab

### ISSUE THREAD

**Issue by ilyasavitski** [sulu/sulu-standard#832]
| Q | A
| --- | ---
| Bug? | idk
| New Feature? | no
| Sulu Version | 1.5.3
| Browser Version | any

For some reason description field editor is hidden on Excerpt & Categories tab of content edit page. How could i fix it?

**Comment by wachterjohannes** [comment]
@ilyasavitski we need here some more information. Are there any JS or Symfony Logs? Have you overwritten the `excerpt.xml` template? can you add a screenshot of your excerpt tab?

**Comment by ilyasavitski** [comment]
![screenshot from 2017-08-02 16-53-36](https://user-images.githubusercontent.com/2191137/28876846-326af410-77a3-11e7-8d53-7b0ac575d221.png)

I haven't overwritten excerpt.xml template.

**Comment by alexander-schranz** [comment]
@ilyasavitski can you run `bin/console doctrine:phpcr:node:dump uuid --props` (uuid id is in your case e244.......28 copy it from the url) and tell what is the value of `i18n:en-excerpt-description`?

**Comment by ilyasavitski** [comment]
`i18n:en-excerpt-description = Devit 50,000 (cholecalciferol) is a drug for treatment and prevention of  of vitamin D deficiency.`

**Comment by alexander-schranz** [comment]
ok seems not be a valid the ckeditor needs a tag (seems to be the text was paste into the source mode and not into the word by paste overlay). at the current state you need to set the property over the phpcr shell:

```bash
bin/adminconsole doctrine:phpcr:shell
cd uuid # your uuid
ls # will show you all props
node:property:set i18n:de-excerpt-description "<p>Devit 50,000 (cholecalciferol) is a drug for treatment and prevention of of vitamin D deficiency.</p>" # will set the new prop
save # save the changes
refresh # load changes
```

**Comment by ilyasavitski** [comment]
Seem's like it didn't help...

Any more ideas?

**Comment by alexander-schranz** [comment]
@ilyasavitski what is the response of the REST API for this description?

**Comment by ilyasavitski** [comment]
> 

@ilyasavitski what is the response of the REST API for this description?
--

How to get t?

**Comment by alexander-schranz** [comment]
have a look at your browser dev tools. `Network` Tab there should be a request with the page uuid.

**Comment by ilyasavitski** [comment]
`{"url":"\/products\/devit-50000","created":"2017-04-25T12:42:51+0300","changed":"2017-07-25T17:30:03+0300","creator":1,"changer":1,"title":"Devit 50000 (Multizan D3 50000)","navContexts":[],"nodeType":1,"nodeState":2,"published":"2017-05-03T04:01:16+0300","shadowOn":false,"shadowBaseLanguage":null,"id":"e2444274-0980-4b85-bed6-a34400048b28","ext":{"seo":{"title":"","description":"","keywords":"","canonicalUrl":"","noIndex":false,"noFollow":false,"hideInSitemap":false},"excerpt":{"title":"","more":"","description":"Devit 50,000 (cholecalciferol) is a drug for treatment and prevention of  of vitamin D deficiency.","categories":[17,21,35,32],"tags":[],"icon":{"displayOption":"top","ids":[]},"images":{"displayOption":"top","ids":[]}}},"order":80,"authored":"2017-04-25","author":1,"_links":{"self":{"href":"\/admin\/api\/nodes\/e2444274-0980-4b85-bed6-a34400048b28?language=en"},"children":{"href":"\/admin\/api\/nodes?parent=e2444274-0980-4b85-bed6-a34400048b28&depth=1&webspace=lamyra_org&language=en"}},"_permissions":{"view":true,"add":true,"edit":true,"delete":true,"archive":true,"live":true,"security":true},"template":"product","originTemplate":"product","internal":false,"localizedTemplate":"Product","images":{"displayOption":"top","ids":[]},"description":"","documents":{"displayOption":"top","ids":[]},"website":"","publications":[],"breadcrumb":[{"uuid":"ae025729-2542-4f66-bf36-54aa07c1b98e","title":"Homepage","depth":0},{"uuid":"ce5f9a1b-cd27-495c-9a76-d56cdfb4c9c6","title":"Products","depth":1}],"path":"\/products\/devit-50000-multizan-d3-50000","parentUuid":"ce5f9a1b-cd27-495c-9a76-d56cdfb4c9c6","concreteLanguages":["en","ru","de"],"enabledShadowLanguages":[],"linked":null,"publishedState":true,"hasSub":false,"_hash":"232e87bcec48dd2097d688c7e9616865"}`

**Comment by alexander-schranz** [comment]
@ilyasavitski seems there is still the old value can you clear the cache

does `bin/adminconsole doctrine:phpcr:node:dump uuid --props` the `description` with the `<p>` tag?  else you did miss to save.

If yes its a caching se so clear the cache with: `bin/adminconsole cache:clear -e <your_environment>`

**Comment by ilyasavitski** [comment]
![screenshot from 2017-08-02 18-54-12](https://user-images.githubusercontent.com/2191137/28882486-09105946-77b4-11e7-8167-a4fc51354ef4.png)
Is i doing something wrong?

**Comment by ilyasavitski** [comment]
Oh...

There should be i18n:en-excerpt-description.

**Comment by ilyasavitski** [comment]
Now it's fixed. Thank you guys!
