### ISSUE TITLE
How does image caching mechanism work?

### ISSUE THREAD

**Issue by ilyasavitski** [sulu/sulu-standard#833]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.5.3

I'm using git to deploy the project to prod server. My .gitignore file has a historical line `/web/uploads`. After update on the prod server seems like images can't be generated or something.

**Comment by ilyasavitski** [comment]
Ok. I got that `var/uploads` is also in .gitignore and it shouldn't be there :)

**Comment by alexander-schranz** [comment]
@ilyasavitski ok good that the issue did solve itself the mechanism is that the image formats are generated on the first request:


![Assets database diagram](https://raw.github.com/massiveart/sulu-docs/master/detail-specification/images/diagrams/ImageProxy.png)

**Comment by alexander-schranz** [comment]
@ilyasavitski and `var/uploads` is in the .gitignore because it should. The images you upload in `dev` should not be in your git repository. They are not referenced in the Production DB and will be garbage there.
