### ISSUE TITLE
In Apache error log: Unknown portal environment "prod" in /var/www/html/sulu-standard-develop/vendor/sulu/sulu/src/Sulu/Component/Webspace/Manager/WebspaceCollection.php:97

### ISSUE THREAD

**Issue by apoorva-shah** [sulu/sulu-standard#834]
I download zip of https://github.com/sulu/sulu-standard
and composer install, I open homepage in browser and i see these errors in apache error log.

PHP Fatal error:  Uncaught InvalidArgumentException: Unknown portal environment "prod" in /var/www/html/sulu-standard-develop/vendor/sulu/sulu/src/Sulu/Component/Webspace/Manager/WebspaceCollection.php:97\nStack trace:\n#0 /var/www/html/sulu-standard-develop/vendor/sulu/sulu/src/Sulu/Component/Webspace/Manager/WebspaceManager.php(104): Sulu\\Component\\Webspace\\Manager\\WebspaceCollection->getPortalInformations('prod')\n#1 /var/www/html/sulu-standard-develop/vendor/sulu/sulu/src/Sulu/Bundle/CustomUrlBundle/Request/CustomUrlRequestProcessor.php(71): Sulu\\Component\\Webspace\\Manager\\WebspaceManager->findPortalInformationsByUrl('localhost/sulu-...', 'prod')\n#2 /var/www/html/sulu-standard-develop/vendor/sulu/sulu/src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php(51): Sulu\\Bundle\\CustomUrlBundle\\Request\\CustomUrlRequestProcessor->process(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Sulu\\Component\\Webspace\\Analyzer\\Attributes\\RequestAttributes))\n#3 /var/www/html/sulu-standard-develop/vendor/sulu/sulu/src/Sulu/Bundle/Webs in /var/www/html/sulu-standard-develop/vendor/sulu/sulu/src/Sulu/Component/Webspace/Manager/WebspaceCollection.php on line 97

**Comment by alexander-schranz** [comment]
@apoorva-shah you did forgot to configure your webspace (app/Resources/webspace/...xml). I would recommend you to use sulu minimal as a start. Just follow the documentation to use it: http://docs.sulu.io/en/latest/book/getting-started.html

**Comment by apoorva-shah** [comment]
Yes issue was my webspoace xml file was sulu.io.xml.dist but it should be sulu.io.xml... So rename and try. issue was solved...
