### ISSUE TITLE
Stored Cross-site Scripting (XSS) in page creation

### ISSUE THREAD

**Issue by ProDigySML** [sulu/sulu-standard#835]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Sulu Version | 1.6.6
| Browser Version | Chrome

#### Actual Behavior

Sulu saves the code unsanitised and allows arbitrary execution of javascript. 

#### Expected Behavior

Sulu should remove the javascript payload as it does for most others. 

#### Steps to Reproduce

1. Log in as a user with page editing permissions
2. Choose to edit an article
3. Add a new block with type text.
4. Click the source code button on the editor and enter the following code: `<p><iframe src="javascript:alert(1)"></iframe></p>`
5. Save the code

#### Possible Solutions

Check iframe src prior to adding to the page.

**Comment by wachterjohannes** [comment]
Thanks for the report :) but we explicitly allow all the HTML tags and attributes in the editor. You can decide if you want to render the content in raw (twig filter). We do this because we don't see the big problem here because the content-manager (logged in system user) should be "competent" enough to avoid it if he doesn't want it.

But we are planning in a future release to make this behavior configurable - there are no concrete plans currently.

/cc @chirimoya @danrot please add your thoughts about this topic

**Comment by danrot** [comment]
I also think that this is the job of the template developer. Especially because I have already seen textareas being used to copy small javascript snippets (e.g. Youtube embed codes).

**Comment by alexander-schranz** [comment]
@floatingbits only the ckeditor run codes but there it is run inside an iframe and should not crash any backend components. and for embed codes its recommend use textareas and not texteditors.

**Comment by floatingbits** [comment]
Hmmm. I do use a textarea. The html is output without any sanitizing to the block preview. 
The code that breaks the whole edit page is a simple vimeo embed code featuring a script tag:

`<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/267254114?title=0&byline=0&portrait=0" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>`

My blocks (without the breaking script tag) look like this: 
![screenshot from 2018-05-09 10-53-28](https://user-images.githubusercontent.com/16322408/39805713-ee58a7fc-5377-11e8-8df0-737c58d552fc.png)
![screenshot from 2018-05-09 10-55-52](https://user-images.githubusercontent.com/16322408/39805726-f4ec1b76-5377-11e8-9749-5c5aad7541e1.png)

**Comment by alexander-schranz** [comment]
for @ProDigySML if you don't want to output something on the website you maybe need to create a custom twig extension using something like http://htmlpurifier.org.

@floatingbits thats good.

I will know close the issue as it seems to be fixed, else feel free to reopen it or add a comment.
