### ISSUE TITLE
How to override a default aura-component

### ISSUE THREAD

**Issue by ichdertobi** [sulu/sulu-standard#838]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no

#### Is there any possibility?
I want to override a/some default aura components, so I could change the standard-theme of (for example) the login. Is this possible? If yes -> how?

**Comment by wachterjohannes** [comment]
@ichdertobi you can use requirejs config to redirect the loading of a component (see https://github.com/sulu/SuluContactExtensionBundle/blob/develop/Resources/public/js/main.js#L13)

**Comment by alexander-schranz** [comment]
if you just want to change the styling create a custom admin bundle and add require your css file there: http://docs.sulu.io/en/latest/bundles/admin/css.html
