### ISSUE TITLE
Missing bin/adminconsole

### ISSUE THREAD

**Issue by tarrasque73** [sulu/sulu-standard#841]
Hi.

Following instructions at http://docs.sulu.io/en/latest/book/getting-started.html I installed sulu-standard with composer on Windows with XAMPP.

php -d memory_limit=-1 composer.phar create-project sulu/sulu-standard sulu -n

Everything seemed to go fine, but there's no adminconsole (or console or webconsole) under bin, so I can not proceed with the database population.

I attach a snapshot of the content of the bin folder.

![image](https://user-images.githubusercontent.com/1118990/36416030-2a499b82-1628-11e8-8ecb-6c513570d9d8.png)

**Comment by wachterjohannes** [comment]
the documentation is build for https://github.com/sulu/sulu-minimal in this repository the adminconsole is simply `bin/console`. if this does not help you feel free to reopen the issue

**Comment by tarrasque73** [comment]
Thanks for the answer.

I get the same result by running php bin/console.

As you can see from my screenshot, the "console" file simply is not in the bin folder.

In facts, there's no bin console at all in the https://github.com/sulu/sulu-standard repository.

Would it work if I just copied the file from https://github.com/sulu/sulu-minimal/bin into my project current bin folder?

**Comment by alexander-schranz** [comment]
@tarrasque73 it seems your system can't autodetect the binary to run the script. try `php bin/console ...` if php is available globally. else you should first add php binary to your PATH that you can access php globally.

**Comment by alexander-schranz** [comment]
@tarrasque73 the console is under `app/console` when using sulu-standard. But I recommend using sulu-minimal NOT sulu-standard to start new projects as it is documented it the docs!

**Comment by tarrasque73** [comment]
Ah got it. Thanks.

One question then. what's the difference then between sulu-minimal. sulu-standard and sulu-complete? when should one use standard or complete in stead of minimal?

**Comment by alexander-schranz** [comment]
@tarrasque73 Short answer always use sulu-minimal long answer can be found  here: https://github.com/sulu/sulu-standard/issues/792#issuecomment-273804627

**Comment by tarrasque73** [comment]
thank you very much for your kind answers. Looking forward to try sulu!
