### ISSUE TITLE
Users can't change their own contact without being able to change all of the contacts

### ISSUE THREAD

**Issue by cdellamonica** [sulu/sulu-standard#851]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.6.21
| Browser Version | any

#### Actual Behavior

Users without rights on "Contacts > people" don't have access to their own contact and can't change their password. In a corporate environnement it represents a security threat.

#### Expected Behavior

One should be able to edit his contact and change his password without being a contacts admin.

#### Steps to Reproduce

Login with a user that does not have a role with the permission "Contacts > people" checked in. Click on the username  in the menu.

#### Possible Solutions

There could be an additional permission "contact > self" that could enable access only to your own contact.

**Comment by danrot** [comment]
You are totally right... We thought more about a separate overlay, and we'll probably implement that in Sulu 2.0. However, this is actually the wrong repo for this kind of issue, can you please create the issue in [sulu/sulu](http://github.com/sulu/sulu) and close this one?

**Comment by cdellamonica** [comment]
Hello Dan, thanks for your answer! I'm going to create this issue in sulu/sulu then.
We're excited about the upcoming sulu 2.0 here and very much looking forward to upgrading to it :)
