### ISSUE TITLE
[TranslateBundle] issue with non-standard translation files sulu:export:translate

### ISSUE THREAD

**Issue by StaffNowa** [sulu/sulu-standard#852]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Sulu/1.6.19
| Browser Version | Google Chrome (not actual)

#### Actual Behavior

How does Sulu behave at the moment? 

When I try generate Dutch - Belgium file sulu.nl_be.json I receive fallback into sulu.nl.json.

#### Expected Behavior

Should get backend.nl_be.xlf translations and generate sulu.nl_be.json

#### Steps to Reproduce

1. Create file for example BusinessBundle/Resources/translations/sulu/backend.nl_be.xlf
2. Try to generate php app/console sulu:translate:export --path public/admin/translations
3. Get sulu.nl_be.json with fallback into sulu.nl.json content. According debugging Symfony do not found nl_be locale

#### Possible Solutions

```
public function execute()
    {
        $messages = [];

        $locale = preg_replace_callback('!b[a-z]!', function($matches) {
            return strtoupper($matches[0]);
        }, $this->getLocale());

        /** @var MessageCatalogueInterface $catalogue */
        $catalogue = $this->translator->getCatalogue($locale);

        if ($this->backend) {
            $messages = array_merge($messages, $this->getMessagesForDomain($catalogue, self::BACKEND_DOMAIN));
        }
        if ($this->frontend) {
            $messages = array_merge($messages, $this->getMessagesForDomain($catalogue, self::FRONTEND_DOMAIN));
        }

        $this->writeMessagesFile($messages);
    }
```

**Comment by StaffNowa** [comment]
File path: vendor/sulu/sulu/src/Sulu/Bundle/TranslateBundle/Translate/Export.php

**Comment by StaffNowa** [comment]
I checked this issue. This is not a bug. False alarm

**Comment by danrot** [comment]
@StaffNowa I guess I can close this issue then. Comment if I am wrong :-) Maybe it would still be useful if you write what the problem was, in case somebody stumbles upon this using Google or something :-)

**Comment by StaffNowa** [comment]
> @StaffNowa I guess I can close this issue then. Comment if I am wrong :-) Maybe it would still be useful if you write what the problem was, in case somebody stumbles upon this using Google or something :-)

I have strange issue 

$request->getLocale() => return nl_be
$translator->getLocale() => return nl_BE

Why I have in controllers issue for bad translation file finding.

**Comment by StaffNowa** [comment]
> @StaffNowa That sounds to me like this is returned like that from Symfony already... I don't think that we touch here anything.

Maybe :) In some cases I need to check locale listener and return good locale name lowercase like we have with Sulu backend.nl_be.xlf file :)

**Comment by danrot** [comment]
@StaffNowa Have you tested if what I said is true? Would be helpful to know :slightly_smiling_face:
