### ISSUE TITLE
Support of PostgreSQL 10

### ISSUE THREAD

**Issue by ichdertobi** [sulu/sulu-standard#853]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | 1.6.21
| Browser Version | -

#### Actual Behavior

Sulu doesnt support PostgeSQL 10. Its not possible to update doctrine/dbal to at least 2.7.0.
If you try to use Sulu with PostgreSQL 10 you get error because of the new sequence-structure:

 An exception occurred while executing 'SELECT min_value, increment_by FROM "ca_categories_id_seq"':

 SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
 LINE 1: SELECT min_value, increment_by FROM "ca_categories_id_seq"
                         ^

#### Expected Behavior

Sulu should also support the newest version of PostgreSQL/ doctrin/dbal2.7.0 at least

**Comment by alexander-schranz** [comment]
Hello @ichdertobi,

there where breaking changes in the doctrine/orm 2.6 release, which will keep us using doctrine/orm 2.5 for the 1.x series (#3696). So if you needed postgresql 10 you should wait for 2.0 release or try a current alpha version of sulu 2.0. As we can't change this for the 1.x series I will close this issue.
