### ISSUE TITLE
bin/adminconsole missing

### ISSUE THREAD

**Issue by ADmad** [sulu/sulu-standard#855]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.22
| OS | Ubuntu 16.04

After creating a new project with 
```
composer create-project sulu/sulu-standard my-project -n
``` 
from the project directory tried running 
```
bin/adminconsole sulu:build dev
```

Ended up with error
```
bash: bin/adminconsole: No such file or directory
```

`adminconsole` is indeed missing from `bin` directory.

To ensure something wasn't messed up in my system I checked creating and setting up project with `sulu/sulu-minimal` and did not have any problems.

**Comment by ADmad** [comment]
Contents of `bin` directory are:
```
$ tree bin
bin
├── behat -> ../vendor/behat/behat/bin/behat
├── doctrine -> ../vendor/doctrine/orm/bin/doctrine
├── doctrine-dbal -> ../vendor/doctrine/dbal/bin/doctrine-dbal
├── doctrine.php -> ../vendor/doctrine/orm/bin/doctrine.php
├── jackalope -> ../vendor/jackalope/jackalope-jackrabbit/bin/jackalope
├── jackrabbit.sh -> ../vendor/jackalope/jackalope-jackrabbit/bin/jackrabbit.sh
├── phpcr -> ../vendor/phpcr/phpcr-utils/bin/phpcr
├── phpcrsh -> ../vendor/phpcr/phpcr-shell/bin/phpcrsh
├── security-checker -> ../vendor/sensiolabs/security-checker/security-checker
└── simple-phpunit -> ../vendor/symfony/phpunit-bridge/bin/simple-phpunit
```

**Comment by alexander-schranz** [comment]
Hello @ADmad,

use as [documented](http://docs.sulu.io/en/latest/book/getting-started.html) the `sulu-minimal` repository to start new documents. This repository is maintained compatibility of old project but not recommended to start a new project. For more information have a look at https://github.com/sulu/sulu-standard/issues/792#issuecomment-273804627. Else feel free to ask a question here or join our [slack channel](https://sulu.io/en#questions)

**Comment by ADmad** [comment]
Okay, thanks.

It would be nice if the readme was updated to mention this and avoid wasting time of everyone involved. :slightly_smiling_face: .

**Comment by alexander-schranz** [comment]
@ADmad thank you I added a note to the [README.md](./..)
