### ISSUE TITLE
Moving media not available at top level

### ISSUE THREAD

**Issue by thgie** [sulu/sulu-standard#857]
| New Feature? | yes
| Sulu Version | 1.6.18

#### Actual Behavior

If user is at top level in Media in Sulu CMS, selected documents and images can' be moved because the option is missing. This can be a problem when user doesn't know where the file resides and uses search at top level, with the intention to move a file.

#### Possible Solutions

Make "Moving media" option be available at top level.

**Comment by alexander-schranz** [comment]
This is now possible in sulu 2.0 to move media directly from the media main view.
